/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.analytics.tables.records;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.analytics.tables.TallCanonical;


/**
 * Canonical tall analytics table. instance_key = COALESCE(repeat_instance_id,
 * submission_uid) used for idempotency
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TallCanonicalRecord extends UpdatableRecordImpl<TallCanonicalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>analytics.tall_canonical.tall_id</code>.
     */
    public void setTallId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.tall_id</code>.
     */
    public Long getTallId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>analytics.tall_canonical.outbox_id</code>.
     */
    public void setOutboxId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.outbox_id</code>.
     */
    public Long getOutboxId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>analytics.tall_canonical.ingest_id</code>.
     */
    public void setIngestId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.ingest_id</code>.
     */
    public UUID getIngestId() {
        return (UUID) get(2);
    }

    /**
     * Setter for
     * <code>analytics.tall_canonical.submission_serial_number</code>.
     */
    public void setSubmissionSerialNumber(Long value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>analytics.tall_canonical.submission_serial_number</code>.
     */
    public Long getSubmissionSerialNumber() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>analytics.tall_canonical.activity_uid</code>.
     */
    public void setActivityUid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.activity_uid</code>.
     */
    public String getActivityUid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>analytics.tall_canonical.org_unit_uid</code>.
     */
    public void setOrgUnitUid(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.org_unit_uid</code>.
     */
    public String getOrgUnitUid() {
        return (String) get(5);
    }

    /**
     * Setter for <code>analytics.tall_canonical.team_uid</code>.
     */
    public void setTeamUid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.team_uid</code>.
     */
    public String getTeamUid() {
        return (String) get(6);
    }

    /**
     * Setter for <code>analytics.tall_canonical.assignment_uid</code>.
     */
    public void setAssignmentUid(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.assignment_uid</code>.
     */
    public String getAssignmentUid() {
        return (String) get(7);
    }

    /**
     * Setter for <code>analytics.tall_canonical.submission_id</code>.
     */
    public void setSubmissionId(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.submission_id</code>.
     */
    public String getSubmissionId() {
        return (String) get(8);
    }

    /**
     * Setter for <code>analytics.tall_canonical.submission_uid</code>.
     */
    public void setSubmissionUid(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.submission_uid</code>.
     */
    public String getSubmissionUid() {
        return (String) get(9);
    }

    /**
     * Setter for <code>analytics.tall_canonical.template_uid</code>.
     */
    public void setTemplateUid(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.template_uid</code>.
     */
    public String getTemplateUid() {
        return (String) get(10);
    }

    /**
     * Setter for <code>analytics.tall_canonical.template_version_uid</code>.
     */
    public void setTemplateVersionUid(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.template_version_uid</code>.
     */
    public String getTemplateVersionUid() {
        return (String) get(11);
    }

    /**
     * Setter for <code>analytics.tall_canonical.instance_key</code>.
     */
    public void setInstanceKey(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.instance_key</code>.
     */
    public String getInstanceKey() {
        return (String) get(12);
    }

    /**
     * Setter for <code>analytics.tall_canonical.canonical_element_id</code>.
     */
    public void setCanonicalElementId(UUID value) {
        set(13, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.canonical_element_id</code>.
     */
    public UUID getCanonicalElementId() {
        return (UUID) get(13);
    }

    /**
     * Setter for <code>analytics.tall_canonical.element_path</code>.
     */
    public void setElementPath(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.element_path</code>.
     */
    public String getElementPath() {
        return (String) get(14);
    }

    /**
     * Setter for <code>analytics.tall_canonical.repeat_instance_id</code>.
     */
    public void setRepeatInstanceId(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.repeat_instance_id</code>.
     */
    public String getRepeatInstanceId() {
        return (String) get(15);
    }

    /**
     * Setter for <code>analytics.tall_canonical.parent_instance_id</code>.
     */
    public void setParentInstanceId(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.parent_instance_id</code>.
     */
    public String getParentInstanceId() {
        return (String) get(16);
    }

    /**
     * Setter for <code>analytics.tall_canonical.repeat_index</code>.
     */
    public void setRepeatIndex(Integer value) {
        set(17, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.repeat_index</code>.
     */
    public Integer getRepeatIndex() {
        return (Integer) get(17);
    }

    /**
     * Setter for <code>analytics.tall_canonical.value_text</code>.
     */
    public void setValueText(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.value_text</code>.
     */
    public String getValueText() {
        return (String) get(18);
    }

    /**
     * Setter for <code>analytics.tall_canonical.value_number</code>.
     */
    public void setValueNumber(BigDecimal value) {
        set(19, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.value_number</code>.
     */
    public BigDecimal getValueNumber() {
        return (BigDecimal) get(19);
    }

    /**
     * Setter for <code>analytics.tall_canonical.value_bool</code>.
     */
    public void setValueBool(Boolean value) {
        set(20, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.value_bool</code>.
     */
    public Boolean getValueBool() {
        return (Boolean) get(20);
    }

    /**
     * Setter for <code>analytics.tall_canonical.value_json</code>.
     */
    public void setValueJson(JSONB value) {
        set(21, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.value_json</code>.
     */
    public JSONB getValueJson() {
        return (JSONB) get(21);
    }

    /**
     * Setter for <code>analytics.tall_canonical.value_ref_uid</code>.
     */
    public void setValueRefUid(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.value_ref_uid</code>.
     */
    public String getValueRefUid() {
        return (String) get(22);
    }

    /**
     * Setter for <code>analytics.tall_canonical.value_ref_type</code>.
     */
    public void setValueRefType(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.value_ref_type</code>.
     */
    public String getValueRefType() {
        return (String) get(23);
    }

    /**
     * Setter for
     * <code>analytics.tall_canonical.submission_creation_time</code>.
     */
    public void setSubmissionCreationTime(LocalDateTime value) {
        set(24, value);
    }

    /**
     * Getter for
     * <code>analytics.tall_canonical.submission_creation_time</code>.
     */
    public LocalDateTime getSubmissionCreationTime() {
        return (LocalDateTime) get(24);
    }

    /**
     * Setter for <code>analytics.tall_canonical.start_time</code>.
     */
    public void setStartTime(LocalDateTime value) {
        set(25, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.start_time</code>.
     */
    public LocalDateTime getStartTime() {
        return (LocalDateTime) get(25);
    }

    /**
     * Setter for <code>analytics.tall_canonical.created_at</code>.
     */
    public void setCreatedAt(LocalDateTime value) {
        set(26, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.created_at</code>.
     */
    public LocalDateTime getCreatedAt() {
        return (LocalDateTime) get(26);
    }

    /**
     * Setter for <code>analytics.tall_canonical.updated_at</code>.
     */
    public void setUpdatedAt(LocalDateTime value) {
        set(27, value);
    }

    /**
     * Getter for <code>analytics.tall_canonical.updated_at</code>.
     */
    public LocalDateTime getUpdatedAt() {
        return (LocalDateTime) get(27);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TallCanonicalRecord
     */
    public TallCanonicalRecord() {
        super(TallCanonical.TALL_CANONICAL);
    }

    /**
     * Create a detached, initialised TallCanonicalRecord
     */
    public TallCanonicalRecord(Long tallId, Long outboxId, UUID ingestId, Long submissionSerialNumber, String activityUid, String orgUnitUid, String teamUid, String assignmentUid, String submissionId, String submissionUid, String templateUid, String templateVersionUid, String instanceKey, UUID canonicalElementId, String elementPath, String repeatInstanceId, String parentInstanceId, Integer repeatIndex, String valueText, BigDecimal valueNumber, Boolean valueBool, JSONB valueJson, String valueRefUid, String valueRefType, LocalDateTime submissionCreationTime, LocalDateTime startTime, LocalDateTime createdAt, LocalDateTime updatedAt) {
        super(TallCanonical.TALL_CANONICAL);

        setTallId(tallId);
        setOutboxId(outboxId);
        setIngestId(ingestId);
        setSubmissionSerialNumber(submissionSerialNumber);
        setActivityUid(activityUid);
        setOrgUnitUid(orgUnitUid);
        setTeamUid(teamUid);
        setAssignmentUid(assignmentUid);
        setSubmissionId(submissionId);
        setSubmissionUid(submissionUid);
        setTemplateUid(templateUid);
        setTemplateVersionUid(templateVersionUid);
        setInstanceKey(instanceKey);
        setCanonicalElementId(canonicalElementId);
        setElementPath(elementPath);
        setRepeatInstanceId(repeatInstanceId);
        setParentInstanceId(parentInstanceId);
        setRepeatIndex(repeatIndex);
        setValueText(valueText);
        setValueNumber(valueNumber);
        setValueBool(valueBool);
        setValueJson(valueJson);
        setValueRefUid(valueRefUid);
        setValueRefType(valueRefType);
        setSubmissionCreationTime(submissionCreationTime);
        setStartTime(startTime);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        resetChangedOnNotNull();
    }
}
