/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Indexes;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.AssignmentMemberRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignmentMember extends TableImpl<AssignmentMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.assignment_member</code>
     */
    public static final AssignmentMember ASSIGNMENT_MEMBER = new AssignmentMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssignmentMemberRecord> getRecordType() {
        return AssignmentMemberRecord.class;
    }

    /**
     * The column <code>public.assignment_member.id</code>.
     */
    public final TableField<AssignmentMemberRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.assignment_member.assignment_id</code>.
     */
    public final TableField<AssignmentMemberRecord, String> ASSIGNMENT_ID = createField(DSL.name("assignment_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.assignment_member.member_type</code>.
     */
    public final TableField<AssignmentMemberRecord, String> MEMBER_TYPE = createField(DSL.name("member_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.assignment_member.member_id</code>.
     */
    public final TableField<AssignmentMemberRecord, String> MEMBER_ID = createField(DSL.name("member_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.assignment_member.role</code>.
     */
    public final TableField<AssignmentMemberRecord, String> ROLE = createField(DSL.name("role"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.assignment_member.valid_from</code>.
     */
    public final TableField<AssignmentMemberRecord, LocalDateTime> VALID_FROM = createField(DSL.name("valid_from"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.assignment_member.valid_to</code>.
     */
    public final TableField<AssignmentMemberRecord, LocalDateTime> VALID_TO = createField(DSL.name("valid_to"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.assignment_member.created_date</code>.
     */
    public final TableField<AssignmentMemberRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.assignment_member.created_by</code>.
     */
    public final TableField<AssignmentMemberRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.assignment_member.last_modified_date</code>.
     */
    public final TableField<AssignmentMemberRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.assignment_member.last_modified_by</code>.
     */
    public final TableField<AssignmentMemberRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private AssignmentMember(Name alias, Table<AssignmentMemberRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AssignmentMember(Name alias, Table<AssignmentMemberRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.assignment_member</code> table reference
     */
    public AssignmentMember(String alias) {
        this(DSL.name(alias), ASSIGNMENT_MEMBER);
    }

    /**
     * Create an aliased <code>public.assignment_member</code> table reference
     */
    public AssignmentMember(Name alias) {
        this(alias, ASSIGNMENT_MEMBER);
    }

    /**
     * Create a <code>public.assignment_member</code> table reference
     */
    public AssignmentMember() {
        this(DSL.name("assignment_member"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_ASSIGNMENT_MEMBER_ASSIGNMENT_ID, Indexes.IDX_ASSIGNMENT_MEMBER_MEMBER, Indexes.IDX_ASSIGNMENT_MEMBER_MEMBER_TYPE, Indexes.IDX_ASSIGNMENT_MEMBER_VALID_TIME);
    }

    @Override
    public Identity<AssignmentMemberRecord, Long> getIdentity() {
        return (Identity<AssignmentMemberRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<AssignmentMemberRecord> getPrimaryKey() {
        return Keys.PK_ASSIGNMENT_MEMBER;
    }

    @Override
    public List<UniqueKey<AssignmentMemberRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_ASSIGNMENT_MEMBER);
    }

    @Override
    public List<ForeignKey<AssignmentMemberRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ASSIGNMENT_MEMBER__FK_ASSIGNMENT_MEMBER_ASSIGNMENT_ID);
    }

    @Override
    public AssignmentMember as(String alias) {
        return new AssignmentMember(DSL.name(alias), this);
    }

    @Override
    public AssignmentMember as(Name alias) {
        return new AssignmentMember(alias, this);
    }

    @Override
    public AssignmentMember as(Table<?> alias) {
        return new AssignmentMember(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AssignmentMember rename(String name) {
        return new AssignmentMember(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssignmentMember rename(Name name) {
        return new AssignmentMember(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssignmentMember rename(Table<?> name) {
        return new AssignmentMember(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssignmentMember where(Condition condition) {
        return new AssignmentMember(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssignmentMember where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssignmentMember where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssignmentMember where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AssignmentMember where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AssignmentMember where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AssignmentMember where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AssignmentMember where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssignmentMember whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssignmentMember whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
