/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Indexes;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.AssignmentPartyBindingRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignmentPartyBinding extends TableImpl<AssignmentPartyBindingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.assignment_party_binding</code>
     */
    public static final AssignmentPartyBinding ASSIGNMENT_PARTY_BINDING = new AssignmentPartyBinding();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssignmentPartyBindingRecord> getRecordType() {
        return AssignmentPartyBindingRecord.class;
    }

    /**
     * The column <code>public.assignment_party_binding.id</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.assignment_party_binding.uid</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.assignment_party_binding.name</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.assignment_party_binding.assignment_id</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, String> ASSIGNMENT_ID = createField(DSL.name("assignment_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.assignment_party_binding.vocabulary_id</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, String> VOCABULARY_ID = createField(DSL.name("vocabulary_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.assignment_party_binding.party_set_id</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, UUID> PARTY_SET_ID = createField(DSL.name("party_set_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.assignment_party_binding.principal_type</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, String> PRINCIPAL_TYPE = createField(DSL.name("principal_type"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.assignment_party_binding.principal_id</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, String> PRINCIPAL_ID = createField(DSL.name("principal_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.assignment_party_binding.combine_mode</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, String> COMBINE_MODE = createField(DSL.name("combine_mode"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>public.assignment_party_binding.created_date</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.assignment_party_binding.created_by</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column
     * <code>public.assignment_party_binding.last_modified_date</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.assignment_party_binding.last_modified_by</code>.
     */
    public final TableField<AssignmentPartyBindingRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private AssignmentPartyBinding(Name alias, Table<AssignmentPartyBindingRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private AssignmentPartyBinding(Name alias, Table<AssignmentPartyBindingRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.assignment_party_binding</code> table
     * reference
     */
    public AssignmentPartyBinding(String alias) {
        this(DSL.name(alias), ASSIGNMENT_PARTY_BINDING);
    }

    /**
     * Create an aliased <code>public.assignment_party_binding</code> table
     * reference
     */
    public AssignmentPartyBinding(Name alias) {
        this(alias, ASSIGNMENT_PARTY_BINDING);
    }

    /**
     * Create a <code>public.assignment_party_binding</code> table reference
     */
    public AssignmentPartyBinding() {
        this(DSL.name("assignment_party_binding"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_APB_ASSIGNMENT_VOCAB_ROLE, Indexes.IDX_APB_PRINCIPAL);
    }

    @Override
    public UniqueKey<AssignmentPartyBindingRecord> getPrimaryKey() {
        return Keys.PK_ASSIGNMENT_PARTY_BINDING;
    }

    @Override
    public List<UniqueKey<AssignmentPartyBindingRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ASSIGNMENT_PARTY_BINDING_UID_KEY, Keys.UX_ASSIGNMENT_PARTY_BINDING_IDS);
    }

    @Override
    public List<ForeignKey<AssignmentPartyBindingRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ASSIGNMENT_PARTY_BINDING__FK_BIND_ASSIGN, Keys.ASSIGNMENT_PARTY_BINDING__FK_BIND_PSET, Keys.ASSIGNMENT_PARTY_BINDING__FK_VOCABULARY_TEMPLATE);
    }

    @Override
    public AssignmentPartyBinding as(String alias) {
        return new AssignmentPartyBinding(DSL.name(alias), this);
    }

    @Override
    public AssignmentPartyBinding as(Name alias) {
        return new AssignmentPartyBinding(alias, this);
    }

    @Override
    public AssignmentPartyBinding as(Table<?> alias) {
        return new AssignmentPartyBinding(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public AssignmentPartyBinding rename(String name) {
        return new AssignmentPartyBinding(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssignmentPartyBinding rename(Name name) {
        return new AssignmentPartyBinding(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public AssignmentPartyBinding rename(Table<?> name) {
        return new AssignmentPartyBinding(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssignmentPartyBinding where(Condition condition) {
        return new AssignmentPartyBinding(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssignmentPartyBinding where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssignmentPartyBinding where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssignmentPartyBinding where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AssignmentPartyBinding where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AssignmentPartyBinding where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AssignmentPartyBinding where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public AssignmentPartyBinding where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssignmentPartyBinding whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public AssignmentPartyBinding whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
