/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.AssignmentRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Assignment extends TableImpl<AssignmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.assignment</code>
     */
    public static final Assignment ASSIGNMENT = new Assignment();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AssignmentRecord> getRecordType() {
        return AssignmentRecord.class;
    }

    /**
     * The column <code>public.assignment.id</code>.
     */
    public final TableField<AssignmentRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.assignment.uid</code>.
     */
    public final TableField<AssignmentRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.assignment.deleted</code>.
     */
    public final TableField<AssignmentRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.assignment.deleted_at</code>.
     */
    public final TableField<AssignmentRecord, LocalDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.assignment.activity_id</code>.
     */
    public final TableField<AssignmentRecord, String> ACTIVITY_ID = createField(DSL.name("activity_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.assignment.start_day</code>.
     */
    public final TableField<AssignmentRecord, Integer> START_DAY = createField(DSL.name("start_day"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.assignment.org_unit_id</code>.
     */
    public final TableField<AssignmentRecord, String> ORG_UNIT_ID = createField(DSL.name("org_unit_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.assignment.team_id</code>.
     */
    public final TableField<AssignmentRecord, String> TEAM_ID = createField(DSL.name("team_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.assignment.path</code>.
     */
    public final TableField<AssignmentRecord, String> PATH = createField(DSL.name("path"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.assignment.level</code>.
     */
    public final TableField<AssignmentRecord, Integer> LEVEL = createField(DSL.name("level"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.assignment.parent_id</code>.
     */
    public final TableField<AssignmentRecord, String> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.assignment.forms</code>.
     */
    public final TableField<AssignmentRecord, JSONB> FORMS = createField(DSL.name("forms"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.assignment.allocated_resources</code>.
     */
    public final TableField<AssignmentRecord, JSONB> ALLOCATED_RESOURCES = createField(DSL.name("allocated_resources"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.assignment.status</code>.
     */
    public final TableField<AssignmentRecord, String> STATUS = createField(DSL.name("status"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.assignment.last_submitted_by</code>.
     */
    public final TableField<AssignmentRecord, String> LAST_SUBMITTED_BY = createField(DSL.name("last_submitted_by"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.assignment.translations</code>.
     */
    public final TableField<AssignmentRecord, JSONB> TRANSLATIONS = createField(DSL.name("translations"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.assignment.created_by</code>.
     */
    public final TableField<AssignmentRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.assignment.created_date</code>.
     */
    public final TableField<AssignmentRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.assignment.last_modified_by</code>.
     */
    public final TableField<AssignmentRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.assignment.last_modified_date</code>.
     */
    public final TableField<AssignmentRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.assignment.properties_map</code>.
     */
    public final TableField<AssignmentRecord, JSONB> PROPERTIES_MAP = createField(DSL.name("properties_map"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.assignment.default_party_set_id</code>.
     */
    public final TableField<AssignmentRecord, UUID> DEFAULT_PARTY_SET_ID = createField(DSL.name("default_party_set_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.assignment.code</code>.
     */
    public final TableField<AssignmentRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.assignment.name</code>.
     */
    public final TableField<AssignmentRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255), this, "");

    private Assignment(Name alias, Table<AssignmentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Assignment(Name alias, Table<AssignmentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.assignment</code> table reference
     */
    public Assignment(String alias) {
        this(DSL.name(alias), ASSIGNMENT);
    }

    /**
     * Create an aliased <code>public.assignment</code> table reference
     */
    public Assignment(Name alias) {
        this(alias, ASSIGNMENT);
    }

    /**
     * Create a <code>public.assignment</code> table reference
     */
    public Assignment() {
        this(DSL.name("assignment"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<AssignmentRecord> getPrimaryKey() {
        return Keys.PK_ASSIGNMENT;
    }

    @Override
    public List<UniqueKey<AssignmentRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.ASSIGNMENT_CODE_KEY, Keys.UC_ASSIGNMENT_ACTIVITY_ID, Keys.UC_ASSIGNMENT_UID);
    }

    @Override
    public List<ForeignKey<AssignmentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ASSIGNMENT__FK_ASSIGNMENT_DEFAULT_PARTY_SET_ID, Keys.ASSIGNMENT__FK_ASSIGNMENT_ON_ACTIVITY, Keys.ASSIGNMENT__FK_ASSIGNMENT_ON_ORGUNIT, Keys.ASSIGNMENT__FK_ASSIGNMENT_ON_PARENT, Keys.ASSIGNMENT__FK_ASSIGNMENT_ON_TEAM);
    }

    @Override
    public Assignment as(String alias) {
        return new Assignment(DSL.name(alias), this);
    }

    @Override
    public Assignment as(Name alias) {
        return new Assignment(alias, this);
    }

    @Override
    public Assignment as(Table<?> alias) {
        return new Assignment(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Assignment rename(String name) {
        return new Assignment(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Assignment rename(Name name) {
        return new Assignment(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Assignment rename(Table<?> name) {
        return new Assignment(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Assignment where(Condition condition) {
        return new Assignment(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Assignment where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Assignment where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Assignment where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Assignment where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Assignment where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Assignment where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Assignment where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Assignment whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Assignment whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
