/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.DataTemplateRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataTemplate extends TableImpl<DataTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.data_template</code>
     */
    public static final DataTemplate DATA_TEMPLATE = new DataTemplate();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataTemplateRecord> getRecordType() {
        return DataTemplateRecord.class;
    }

    /**
     * The column <code>public.data_template.id</code>.
     */
    public final TableField<DataTemplateRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.data_template.uid</code>.
     */
    public final TableField<DataTemplateRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.data_template.code</code>.
     */
    public final TableField<DataTemplateRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.data_template.name</code>.
     */
    public final TableField<DataTemplateRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.data_template.version_uid</code>.
     */
    public final TableField<DataTemplateRecord, String> VERSION_UID = createField(DSL.name("version_uid"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.data_template.version_number</code>.
     */
    public final TableField<DataTemplateRecord, Integer> VERSION_NUMBER = createField(DSL.name("version_number"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.data_template.deleted</code>.
     */
    public final TableField<DataTemplateRecord, Boolean> DELETED = createField(DSL.name("deleted"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.data_template.deleted_at</code>.
     */
    public final TableField<DataTemplateRecord, LocalDateTime> DELETED_AT = createField(DSL.name("deleted_at"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_template.description</code>.
     */
    public final TableField<DataTemplateRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(2000), this, "");

    /**
     * The column <code>public.data_template.translations</code>.
     */
    public final TableField<DataTemplateRecord, JSONB> TRANSLATIONS = createField(DSL.name("translations"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.data_template.created_by</code>.
     */
    public final TableField<DataTemplateRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.data_template.created_date</code>.
     */
    public final TableField<DataTemplateRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_template.last_modified_by</code>.
     */
    public final TableField<DataTemplateRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.data_template.last_modified_date</code>.
     */
    public final TableField<DataTemplateRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_template.properties_map</code>.
     */
    public final TableField<DataTemplateRecord, JSONB> PROPERTIES_MAP = createField(DSL.name("properties_map"), SQLDataType.JSONB, this, "");

    private DataTemplate(Name alias, Table<DataTemplateRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DataTemplate(Name alias, Table<DataTemplateRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.data_template</code> table reference
     */
    public DataTemplate(String alias) {
        this(DSL.name(alias), DATA_TEMPLATE);
    }

    /**
     * Create an aliased <code>public.data_template</code> table reference
     */
    public DataTemplate(Name alias) {
        this(alias, DATA_TEMPLATE);
    }

    /**
     * Create a <code>public.data_template</code> table reference
     */
    public DataTemplate() {
        this(DSL.name("data_template"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<DataTemplateRecord> getPrimaryKey() {
        return Keys.PK_DATA_TEMPLATE;
    }

    @Override
    public List<UniqueKey<DataTemplateRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_DATA_TEMPLATE_CODE, Keys.UC_DATA_TEMPLATE_NAME, Keys.UC_DATA_TEMPLATE_UID, Keys.UC_DATA_TEMPLATE_VERSION_UID);
    }

    @Override
    public DataTemplate as(String alias) {
        return new DataTemplate(DSL.name(alias), this);
    }

    @Override
    public DataTemplate as(Name alias) {
        return new DataTemplate(alias, this);
    }

    @Override
    public DataTemplate as(Table<?> alias) {
        return new DataTemplate(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DataTemplate rename(String name) {
        return new DataTemplate(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataTemplate rename(Name name) {
        return new DataTemplate(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataTemplate rename(Table<?> name) {
        return new DataTemplate(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataTemplate where(Condition condition) {
        return new DataTemplate(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataTemplate where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataTemplate where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataTemplate where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataTemplate where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataTemplate where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataTemplate where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataTemplate where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataTemplate whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataTemplate whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
