/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Indexes;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.DataTemplateVersionRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataTemplateVersion extends TableImpl<DataTemplateVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.data_template_version</code>
     */
    public static final DataTemplateVersion DATA_TEMPLATE_VERSION = new DataTemplateVersion();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DataTemplateVersionRecord> getRecordType() {
        return DataTemplateVersionRecord.class;
    }

    /**
     * The column <code>public.data_template_version.id</code>.
     */
    public final TableField<DataTemplateVersionRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.data_template_version.uid</code>.
     */
    public final TableField<DataTemplateVersionRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.data_template_version.template_uid</code>.
     */
    public final TableField<DataTemplateVersionRecord, String> TEMPLATE_UID = createField(DSL.name("template_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.data_template_version.version_number</code>.
     */
    public final TableField<DataTemplateVersionRecord, Integer> VERSION_NUMBER = createField(DSL.name("version_number"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.data_template_version.release_notes</code>.
     */
    public final TableField<DataTemplateVersionRecord, String> RELEASE_NOTES = createField(DSL.name("release_notes"), SQLDataType.VARCHAR(4000), this, "");

    /**
     * The column <code>public.data_template_version.fields</code>.
     */
    public final TableField<DataTemplateVersionRecord, JSONB> FIELDS = createField(DSL.name("fields"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.data_template_version.sections</code>.
     */
    public final TableField<DataTemplateVersionRecord, JSONB> SECTIONS = createField(DSL.name("sections"), SQLDataType.JSONB.nullable(false), this, "");

    /**
     * The column <code>public.data_template_version.data_template_id</code>.
     */
    public final TableField<DataTemplateVersionRecord, String> DATA_TEMPLATE_ID = createField(DSL.name("data_template_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.data_template_version.created_by</code>.
     */
    public final TableField<DataTemplateVersionRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.data_template_version.last_modified_by</code>.
     */
    public final TableField<DataTemplateVersionRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.data_template_version.created_date</code>.
     */
    public final TableField<DataTemplateVersionRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_template_version.last_modified_date</code>.
     */
    public final TableField<DataTemplateVersionRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.data_template_version.options</code>.
     */
    public final TableField<DataTemplateVersionRecord, JSONB> OPTIONS = createField(DSL.name("options"), SQLDataType.JSONB, this, "");

    private DataTemplateVersion(Name alias, Table<DataTemplateVersionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private DataTemplateVersion(Name alias, Table<DataTemplateVersionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.data_template_version</code> table
     * reference
     */
    public DataTemplateVersion(String alias) {
        this(DSL.name(alias), DATA_TEMPLATE_VERSION);
    }

    /**
     * Create an aliased <code>public.data_template_version</code> table
     * reference
     */
    public DataTemplateVersion(Name alias) {
        this(alias, DATA_TEMPLATE_VERSION);
    }

    /**
     * Create a <code>public.data_template_version</code> table reference
     */
    public DataTemplateVersion() {
        this(DSL.name("data_template_version"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TV_TEMPLATE_UID, Indexes.IDX_TV_TEMPLATE_UID_VERSION_DESC, Indexes.IDX_TV_VERSION_NO);
    }

    @Override
    public UniqueKey<DataTemplateVersionRecord> getPrimaryKey() {
        return Keys.PK_DATA_TEMPLATE_VERSION;
    }

    @Override
    public List<UniqueKey<DataTemplateVersionRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_TEMPLATE_VERSION_UID, Keys.UX_TV_ID_DATA_TEMPLATE_ID, Keys.UX_TV_NO_DATA_TEMPLATE_ID);
    }

    @Override
    public List<ForeignKey<DataTemplateVersionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.DATA_TEMPLATE_VERSION__FK_DATA_TEMPLATE_VERSION_ON_DATA_TEMPLATE);
    }

    @Override
    public DataTemplateVersion as(String alias) {
        return new DataTemplateVersion(DSL.name(alias), this);
    }

    @Override
    public DataTemplateVersion as(Name alias) {
        return new DataTemplateVersion(alias, this);
    }

    @Override
    public DataTemplateVersion as(Table<?> alias) {
        return new DataTemplateVersion(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public DataTemplateVersion rename(String name) {
        return new DataTemplateVersion(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataTemplateVersion rename(Name name) {
        return new DataTemplateVersion(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public DataTemplateVersion rename(Table<?> name) {
        return new DataTemplateVersion(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataTemplateVersion where(Condition condition) {
        return new DataTemplateVersion(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataTemplateVersion where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataTemplateVersion where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataTemplateVersion where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataTemplateVersion where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataTemplateVersion where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataTemplateVersion where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public DataTemplateVersion where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataTemplateVersion whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public DataTemplateVersion whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
