/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.OrgUnitRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgUnit extends TableImpl<OrgUnitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.org_unit</code>
     */
    public static final OrgUnit ORG_UNIT = new OrgUnit();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<OrgUnitRecord> getRecordType() {
        return OrgUnitRecord.class;
    }

    /**
     * The column <code>public.org_unit.id</code>.
     */
    public final TableField<OrgUnitRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.org_unit.uid</code>.
     */
    public final TableField<OrgUnitRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.org_unit.code</code>.
     */
    public final TableField<OrgUnitRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.org_unit.name</code>.
     */
    public final TableField<OrgUnitRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.org_unit.path</code>.
     */
    public final TableField<OrgUnitRecord, String> PATH = createField(DSL.name("path"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.org_unit.level</code>.
     */
    public final TableField<OrgUnitRecord, Integer> LEVEL = createField(DSL.name("level"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>public.org_unit.parent_id</code>.
     */
    public final TableField<OrgUnitRecord, String> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.org_unit.translations</code>.
     */
    public final TableField<OrgUnitRecord, JSONB> TRANSLATIONS = createField(DSL.name("translations"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.org_unit.created_by</code>.
     */
    public final TableField<OrgUnitRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.org_unit.created_date</code>.
     */
    public final TableField<OrgUnitRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.org_unit.last_modified_by</code>.
     */
    public final TableField<OrgUnitRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.org_unit.last_modified_date</code>.
     */
    public final TableField<OrgUnitRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.org_unit.properties_map</code>.
     */
    public final TableField<OrgUnitRecord, JSONB> PROPERTIES_MAP = createField(DSL.name("properties_map"), SQLDataType.JSONB, this, "");

    private OrgUnit(Name alias, Table<OrgUnitRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private OrgUnit(Name alias, Table<OrgUnitRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.org_unit</code> table reference
     */
    public OrgUnit(String alias) {
        this(DSL.name(alias), ORG_UNIT);
    }

    /**
     * Create an aliased <code>public.org_unit</code> table reference
     */
    public OrgUnit(Name alias) {
        this(alias, ORG_UNIT);
    }

    /**
     * Create a <code>public.org_unit</code> table reference
     */
    public OrgUnit() {
        this(DSL.name("org_unit"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<OrgUnitRecord> getPrimaryKey() {
        return Keys.PK_ORG_UNIT;
    }

    @Override
    public List<UniqueKey<OrgUnitRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_ORG_UNIT_CODE, Keys.UC_ORG_UNIT_UID);
    }

    @Override
    public List<ForeignKey<OrgUnitRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ORG_UNIT__FK_ORG_UNIT_ON_PARENT);
    }

    @Override
    public OrgUnit as(String alias) {
        return new OrgUnit(DSL.name(alias), this);
    }

    @Override
    public OrgUnit as(Name alias) {
        return new OrgUnit(alias, this);
    }

    @Override
    public OrgUnit as(Table<?> alias) {
        return new OrgUnit(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnit rename(String name) {
        return new OrgUnit(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnit rename(Name name) {
        return new OrgUnit(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public OrgUnit rename(Table<?> name) {
        return new OrgUnit(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnit where(Condition condition) {
        return new OrgUnit(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnit where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnit where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnit where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnit where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnit where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnit where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public OrgUnit where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnit whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public OrgUnit whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
