/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Indexes;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.PartySetRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartySet extends TableImpl<PartySetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.party_set</code>
     */
    public static final PartySet PARTY_SET = new PartySet();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PartySetRecord> getRecordType() {
        return PartySetRecord.class;
    }

    /**
     * The column <code>public.party_set.id</code>.
     */
    public final TableField<PartySetRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.party_set.uid</code>.
     */
    public final TableField<PartySetRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.party_set.code</code>.
     */
    public final TableField<PartySetRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>public.party_set.name</code>.
     */
    public final TableField<PartySetRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.party_set.kind</code>.
     */
    public final TableField<PartySetRecord, String> KIND = createField(DSL.name("kind"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.party_set.spec</code>.
     */
    public final TableField<PartySetRecord, JSONB> SPEC = createField(DSL.name("spec"), SQLDataType.JSONB.nullable(false).defaultValue(DSL.field(DSL.raw("'{}'::jsonb"), SQLDataType.JSONB)), this, "");

    /**
     * The column <code>public.party_set.is_materialized</code>.
     */
    public final TableField<PartySetRecord, Boolean> IS_MATERIALIZED = createField(DSL.name("is_materialized"), SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)), this, "");

    /**
     * The column <code>public.party_set.created_date</code>.
     */
    public final TableField<PartySetRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.party_set.created_by</code>.
     */
    public final TableField<PartySetRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.party_set.last_modified_date</code>.
     */
    public final TableField<PartySetRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.party_set.last_modified_by</code>.
     */
    public final TableField<PartySetRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.party_set.translations</code>.
     */
    public final TableField<PartySetRecord, JSONB> TRANSLATIONS = createField(DSL.name("translations"), SQLDataType.JSONB.defaultValue(DSL.field(DSL.raw("'[]'::jsonb"), SQLDataType.JSONB)), this, "");

    private PartySet(Name alias, Table<PartySetRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PartySet(Name alias, Table<PartySetRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.party_set</code> table reference
     */
    public PartySet(String alias) {
        this(DSL.name(alias), PARTY_SET);
    }

    /**
     * Create an aliased <code>public.party_set</code> table reference
     */
    public PartySet(Name alias) {
        this(alias, PARTY_SET);
    }

    /**
     * Create a <code>public.party_set</code> table reference
     */
    public PartySet() {
        this(DSL.name("party_set"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PARTY_SET_KIND, Indexes.IDX_PARTY_SET_UID);
    }

    @Override
    public UniqueKey<PartySetRecord> getPrimaryKey() {
        return Keys.PK_PARTY_SET;
    }

    @Override
    public List<UniqueKey<PartySetRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PARTY_SET_CODE_KEY, Keys.PARTY_SET_UID_KEY);
    }

    @Override
    public PartySet as(String alias) {
        return new PartySet(DSL.name(alias), this);
    }

    @Override
    public PartySet as(Name alias) {
        return new PartySet(alias, this);
    }

    @Override
    public PartySet as(Table<?> alias) {
        return new PartySet(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PartySet rename(String name) {
        return new PartySet(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PartySet rename(Name name) {
        return new PartySet(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PartySet rename(Table<?> name) {
        return new PartySet(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartySet where(Condition condition) {
        return new PartySet(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartySet where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartySet where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartySet where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PartySet where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PartySet where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PartySet where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PartySet where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartySet whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartySet whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
