/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Indexes;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.PartyRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Party extends TableImpl<PartyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.party</code>
     */
    public static final Party PARTY = new Party();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PartyRecord> getRecordType() {
        return PartyRecord.class;
    }

    /**
     * The column <code>public.party.id</code>.
     */
    public final TableField<PartyRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.party.uid</code>.
     */
    public final TableField<PartyRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.party.code</code>.
     */
    public final TableField<PartyRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(32), this, "");

    /**
     * The column <code>public.party.name</code>.
     */
    public final TableField<PartyRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.party.type</code>.
     */
    public final TableField<PartyRecord, String> TYPE = createField(DSL.name("type"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.party.source_type</code>.
     */
    public final TableField<PartyRecord, String> SOURCE_TYPE = createField(DSL.name("source_type"), SQLDataType.VARCHAR(32).nullable(false), this, "");

    /**
     * The column <code>public.party.source_id</code>.
     */
    public final TableField<PartyRecord, String> SOURCE_ID = createField(DSL.name("source_id"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column <code>public.party.created_date</code>.
     */
    public final TableField<PartyRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.party.created_by</code>.
     */
    public final TableField<PartyRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.party.last_modified_date</code>.
     */
    public final TableField<PartyRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6).nullable(false), this, "");

    /**
     * The column <code>public.party.last_modified_by</code>.
     */
    public final TableField<PartyRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.party.parent_id</code>.
     */
    public final TableField<PartyRecord, UUID> PARENT_ID = createField(DSL.name("parent_id"), SQLDataType.UUID, this, "");

    /**
     * The column <code>public.party.translations</code>.
     */
    public final TableField<PartyRecord, JSONB> TRANSLATIONS = createField(DSL.name("translations"), SQLDataType.JSONB.defaultValue(DSL.field(DSL.raw("'[]'::jsonb"), SQLDataType.JSONB)), this, "");

    private Party(Name alias, Table<PartyRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Party(Name alias, Table<PartyRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.party</code> table reference
     */
    public Party(String alias) {
        this(DSL.name(alias), PARTY);
    }

    /**
     * Create an aliased <code>public.party</code> table reference
     */
    public Party(Name alias) {
        this(alias, PARTY);
    }

    /**
     * Create a <code>public.party</code> table reference
     */
    public Party() {
        this(DSL.name("party"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PARTY_PARENT, Indexes.IDX_PARTY_SOURCE, Indexes.IDX_PARTY_UID);
    }

    @Override
    public UniqueKey<PartyRecord> getPrimaryKey() {
        return Keys.PK_PARTY;
    }

    @Override
    public List<UniqueKey<PartyRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.PARTY_SOURCE_ID_KEY, Keys.PARTY_UID_KEY, Keys.UQ_PARTY_SOURCE);
    }

    @Override
    public List<ForeignKey<PartyRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PARTY__FK_PARTY_PARENT);
    }

    @Override
    public Party as(String alias) {
        return new Party(DSL.name(alias), this);
    }

    @Override
    public Party as(Name alias) {
        return new Party(alias, this);
    }

    @Override
    public Party as(Table<?> alias) {
        return new Party(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Party rename(String name) {
        return new Party(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Party rename(Name name) {
        return new Party(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Party rename(Table<?> name) {
        return new Party(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Party where(Condition condition) {
        return new Party(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Party where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Party where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Party where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Party where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Party where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Party where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Party where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Party whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Party whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
