/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Indexes;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.PartySetMemberRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartySetMember extends TableImpl<PartySetMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.party_set_member</code>
     */
    public static final PartySetMember PARTY_SET_MEMBER = new PartySetMember();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PartySetMemberRecord> getRecordType() {
        return PartySetMemberRecord.class;
    }

    /**
     * The column <code>public.party_set_member.id</code>.
     */
    public final TableField<PartySetMemberRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.party_set_member.party_set_id</code>.
     */
    public final TableField<PartySetMemberRecord, UUID> PARTY_SET_ID = createField(DSL.name("party_set_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.party_set_member.party_id</code>.
     */
    public final TableField<PartySetMemberRecord, UUID> PARTY_ID = createField(DSL.name("party_id"), SQLDataType.UUID.nullable(false), this, "");

    private PartySetMember(Name alias, Table<PartySetMemberRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PartySetMember(Name alias, Table<PartySetMemberRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.party_set_member</code> table reference
     */
    public PartySetMember(String alias) {
        this(DSL.name(alias), PARTY_SET_MEMBER);
    }

    /**
     * Create an aliased <code>public.party_set_member</code> table reference
     */
    public PartySetMember(Name alias) {
        this(alias, PARTY_SET_MEMBER);
    }

    /**
     * Create a <code>public.party_set_member</code> table reference
     */
    public PartySetMember() {
        this(DSL.name("party_set_member"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PSM_PARTY_ID);
    }

    @Override
    public Identity<PartySetMemberRecord, Long> getIdentity() {
        return (Identity<PartySetMemberRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PartySetMemberRecord> getPrimaryKey() {
        return Keys.PK_PARTY_SET_MEMBER;
    }

    @Override
    public List<UniqueKey<PartySetMemberRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UX_PARTY_SET_MEMBER_PARTY);
    }

    @Override
    public List<ForeignKey<PartySetMemberRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PARTY_SET_MEMBER__FK_PSM_PARTY, Keys.PARTY_SET_MEMBER__FK_PSM_PARTY_SET);
    }

    @Override
    public PartySetMember as(String alias) {
        return new PartySetMember(DSL.name(alias), this);
    }

    @Override
    public PartySetMember as(Name alias) {
        return new PartySetMember(alias, this);
    }

    @Override
    public PartySetMember as(Table<?> alias) {
        return new PartySetMember(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PartySetMember rename(String name) {
        return new PartySetMember(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PartySetMember rename(Name name) {
        return new PartySetMember(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PartySetMember rename(Table<?> name) {
        return new PartySetMember(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartySetMember where(Condition condition) {
        return new PartySetMember(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartySetMember where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartySetMember where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartySetMember where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PartySetMember where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PartySetMember where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PartySetMember where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PartySetMember where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartySetMember whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartySetMember whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
