/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Indexes;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.PartyTagRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartyTag extends TableImpl<PartyTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.party_tag</code>
     */
    public static final PartyTag PARTY_TAG = new PartyTag();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PartyTagRecord> getRecordType() {
        return PartyTagRecord.class;
    }

    /**
     * The column <code>public.party_tag.id</code>.
     */
    public final TableField<PartyTagRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.party_tag.party_id</code>.
     */
    public final TableField<PartyTagRecord, UUID> PARTY_ID = createField(DSL.name("party_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.party_tag.tag_key</code>.
     */
    public final TableField<PartyTagRecord, String> TAG_KEY = createField(DSL.name("tag_key"), SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>public.party_tag.tag_value</code>.
     */
    public final TableField<PartyTagRecord, String> TAG_VALUE = createField(DSL.name("tag_value"), SQLDataType.VARCHAR(100), this, "");

    /**
     * The column <code>public.party_tag.meta</code>.
     */
    public final TableField<PartyTagRecord, JSONB> META = createField(DSL.name("meta"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.party_tag.created_date</code>.
     */
    public final TableField<PartyTagRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.party_tag.created_by</code>.
     */
    public final TableField<PartyTagRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private PartyTag(Name alias, Table<PartyTagRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private PartyTag(Name alias, Table<PartyTagRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.party_tag</code> table reference
     */
    public PartyTag(String alias) {
        this(DSL.name(alias), PARTY_TAG);
    }

    /**
     * Create an aliased <code>public.party_tag</code> table reference
     */
    public PartyTag(Name alias) {
        this(alias, PARTY_TAG);
    }

    /**
     * Create a <code>public.party_tag</code> table reference
     */
    public PartyTag() {
        this(DSL.name("party_tag"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_PARTY_TAG_KEY, Indexes.IDX_PARTY_TAG_KEY_VALUE);
    }

    @Override
    public Identity<PartyTagRecord, Long> getIdentity() {
        return (Identity<PartyTagRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<PartyTagRecord> getPrimaryKey() {
        return Keys.PK_PARTY_TAG;
    }

    @Override
    public List<UniqueKey<PartyTagRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_PARTY_TAG_KEY_VALUE);
    }

    @Override
    public List<ForeignKey<PartyTagRecord, ?>> getReferences() {
        return Arrays.asList(Keys.PARTY_TAG__FK_PARTY_TAG);
    }

    @Override
    public PartyTag as(String alias) {
        return new PartyTag(DSL.name(alias), this);
    }

    @Override
    public PartyTag as(Name alias) {
        return new PartyTag(alias, this);
    }

    @Override
    public PartyTag as(Table<?> alias) {
        return new PartyTag(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public PartyTag rename(String name) {
        return new PartyTag(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PartyTag rename(Name name) {
        return new PartyTag(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public PartyTag rename(Table<?> name) {
        return new PartyTag(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartyTag where(Condition condition) {
        return new PartyTag(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartyTag where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartyTag where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartyTag where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PartyTag where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PartyTag where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PartyTag where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public PartyTag where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartyTag whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public PartyTag whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
