/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.TeamRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Team extends TableImpl<TeamRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.team</code>
     */
    public static final Team TEAM = new Team();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeamRecord> getRecordType() {
        return TeamRecord.class;
    }

    /**
     * The column <code>public.team.id</code>.
     */
    public final TableField<TeamRecord, String> ID = createField(DSL.name("id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.team.uid</code>.
     */
    public final TableField<TeamRecord, String> UID = createField(DSL.name("uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>public.team.code</code>.
     */
    public final TableField<TeamRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.team.name</code>.
     */
    public final TableField<TeamRecord, String> NAME = createField(DSL.name("name"), SQLDataType.VARCHAR(255).nullable(false), this, "");

    /**
     * The column <code>public.team.description</code>.
     */
    public final TableField<TeamRecord, String> DESCRIPTION = createField(DSL.name("description"), SQLDataType.VARCHAR(255), this, "");

    /**
     * The column <code>public.team.disabled</code>.
     */
    public final TableField<TeamRecord, Boolean> DISABLED = createField(DSL.name("disabled"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>public.team.activity_id</code>.
     */
    public final TableField<TeamRecord, String> ACTIVITY_ID = createField(DSL.name("activity_id"), SQLDataType.VARCHAR(26), this, "");

    /**
     * The column <code>public.team.form_permissions</code>.
     */
    public final TableField<TeamRecord, JSONB> FORM_PERMISSIONS = createField(DSL.name("form_permissions"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.team.translations</code>.
     */
    public final TableField<TeamRecord, JSONB> TRANSLATIONS = createField(DSL.name("translations"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>public.team.created_by</code>.
     */
    public final TableField<TeamRecord, String> CREATED_BY = createField(DSL.name("created_by"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.team.created_date</code>.
     */
    public final TableField<TeamRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.team.last_modified_by</code>.
     */
    public final TableField<TeamRecord, String> LAST_MODIFIED_BY = createField(DSL.name("last_modified_by"), SQLDataType.VARCHAR(50), this, "");

    /**
     * The column <code>public.team.last_modified_date</code>.
     */
    public final TableField<TeamRecord, LocalDateTime> LAST_MODIFIED_DATE = createField(DSL.name("last_modified_date"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>public.team.properties_map</code>.
     */
    public final TableField<TeamRecord, JSONB> PROPERTIES_MAP = createField(DSL.name("properties_map"), SQLDataType.JSONB, this, "");

    private Team(Name alias, Table<TeamRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Team(Name alias, Table<TeamRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.team</code> table reference
     */
    public Team(String alias) {
        this(DSL.name(alias), TEAM);
    }

    /**
     * Create an aliased <code>public.team</code> table reference
     */
    public Team(Name alias) {
        this(alias, TEAM);
    }

    /**
     * Create a <code>public.team</code> table reference
     */
    public Team() {
        this(DSL.name("team"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TeamRecord> getPrimaryKey() {
        return Keys.PK_TEAM;
    }

    @Override
    public List<UniqueKey<TeamRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UC_TEAM_CODE_ACTIVITY_ID, Keys.UC_TEAM_UID);
    }

    @Override
    public List<ForeignKey<TeamRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TEAM__FK_TEAM_ON_ACTIVITY);
    }

    @Override
    public Team as(String alias) {
        return new Team(DSL.name(alias), this);
    }

    @Override
    public Team as(Name alias) {
        return new Team(alias, this);
    }

    @Override
    public Team as(Table<?> alias) {
        return new Team(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Team rename(String name) {
        return new Team(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Team rename(Name name) {
        return new Team(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Team rename(Table<?> name) {
        return new Team(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Team where(Condition condition) {
        return new Team(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Team where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Team where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Team where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Team where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Team where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Team where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Team where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Team whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Team whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
