/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.TeamUserRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamUser extends TableImpl<TeamUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.team_user</code>
     */
    public static final TeamUser TEAM_USER = new TeamUser();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TeamUserRecord> getRecordType() {
        return TeamUserRecord.class;
    }

    /**
     * The column <code>public.team_user.team_id</code>.
     */
    public final TableField<TeamUserRecord, String> TEAM_ID = createField(DSL.name("team_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.team_user.user_id</code>.
     */
    public final TableField<TeamUserRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    private TeamUser(Name alias, Table<TeamUserRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TeamUser(Name alias, Table<TeamUserRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.team_user</code> table reference
     */
    public TeamUser(String alias) {
        this(DSL.name(alias), TEAM_USER);
    }

    /**
     * Create an aliased <code>public.team_user</code> table reference
     */
    public TeamUser(Name alias) {
        this(alias, TEAM_USER);
    }

    /**
     * Create a <code>public.team_user</code> table reference
     */
    public TeamUser() {
        this(DSL.name("team_user"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TeamUserRecord> getPrimaryKey() {
        return Keys.PK_TEAM_USER;
    }

    @Override
    public List<ForeignKey<TeamUserRecord, ?>> getReferences() {
        return Arrays.asList(Keys.TEAM_USER__FK_TEAM_USER_ON_TEAM, Keys.TEAM_USER__FK_TEAM_USER_ON_USER);
    }

    @Override
    public TeamUser as(String alias) {
        return new TeamUser(DSL.name(alias), this);
    }

    @Override
    public TeamUser as(Name alias) {
        return new TeamUser(alias, this);
    }

    @Override
    public TeamUser as(Table<?> alias) {
        return new TeamUser(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamUser rename(String name) {
        return new TeamUser(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamUser rename(Name name) {
        return new TeamUser(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TeamUser rename(Table<?> name) {
        return new TeamUser(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamUser where(Condition condition) {
        return new TeamUser(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamUser where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamUser where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamUser where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamUser where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamUser where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamUser where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TeamUser where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamUser whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TeamUser whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
