/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Indexes;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.UserExecutionContextRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserExecutionContext extends TableImpl<UserExecutionContextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_execution_context</code>
     */
    public static final UserExecutionContext USER_EXECUTION_CONTEXT = new UserExecutionContext();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserExecutionContextRecord> getRecordType() {
        return UserExecutionContextRecord.class;
    }

    /**
     * The column <code>public.user_execution_context.id</code>.
     */
    public final TableField<UserExecutionContextRecord, Long> ID = createField(DSL.name("id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.user_execution_context.user_uid</code>.
     */
    public final TableField<UserExecutionContextRecord, String> USER_UID = createField(DSL.name("user_uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>public.user_execution_context.entity_type</code>.
     */
    public final TableField<UserExecutionContextRecord, String> ENTITY_TYPE = createField(DSL.name("entity_type"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column <code>public.user_execution_context.entity_uid</code>.
     */
    public final TableField<UserExecutionContextRecord, String> ENTITY_UID = createField(DSL.name("entity_uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column
     * <code>public.user_execution_context.resolved_permission</code>.
     */
    public final TableField<UserExecutionContextRecord, String> RESOLVED_PERMISSION = createField(DSL.name("resolved_permission"), SQLDataType.VARCHAR(20).nullable(false), this, "");

    /**
     * The column <code>public.user_execution_context.created_date</code>.
     */
    public final TableField<UserExecutionContextRecord, LocalDateTime> CREATED_DATE = createField(DSL.name("created_date"), SQLDataType.LOCALDATETIME(6).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>public.user_execution_context.provenance</code>.
     */
    public final TableField<UserExecutionContextRecord, JSONB> PROVENANCE = createField(DSL.name("provenance"), SQLDataType.JSONB, this, "");

    private UserExecutionContext(Name alias, Table<UserExecutionContextRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserExecutionContext(Name alias, Table<UserExecutionContextRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_execution_context</code> table
     * reference
     */
    public UserExecutionContext(String alias) {
        this(DSL.name(alias), USER_EXECUTION_CONTEXT);
    }

    /**
     * Create an aliased <code>public.user_execution_context</code> table
     * reference
     */
    public UserExecutionContext(Name alias) {
        this(alias, USER_EXECUTION_CONTEXT);
    }

    /**
     * Create a <code>public.user_execution_context</code> table reference
     */
    public UserExecutionContext() {
        this(DSL.name("user_execution_context"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_UEC_ENTITY);
    }

    @Override
    public Identity<UserExecutionContextRecord, Long> getIdentity() {
        return (Identity<UserExecutionContextRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<UserExecutionContextRecord> getPrimaryKey() {
        return Keys.USER_EXECUTION_CONTEXT_PKEY;
    }

    @Override
    public List<UniqueKey<UserExecutionContextRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UK_UEC_USER_ENTITY);
    }

    @Override
    public UserExecutionContext as(String alias) {
        return new UserExecutionContext(DSL.name(alias), this);
    }

    @Override
    public UserExecutionContext as(Name alias) {
        return new UserExecutionContext(alias, this);
    }

    @Override
    public UserExecutionContext as(Table<?> alias) {
        return new UserExecutionContext(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserExecutionContext rename(String name) {
        return new UserExecutionContext(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserExecutionContext rename(Name name) {
        return new UserExecutionContext(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserExecutionContext rename(Table<?> name) {
        return new UserExecutionContext(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserExecutionContext where(Condition condition) {
        return new UserExecutionContext(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserExecutionContext where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserExecutionContext where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserExecutionContext where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserExecutionContext where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserExecutionContext where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserExecutionContext where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserExecutionContext where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserExecutionContext whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserExecutionContext whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
