/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.public_.Keys;
import org.nmcpye.datarun.jooq.public_.Public;
import org.nmcpye.datarun.jooq.public_.tables.records.UserGroupUsersRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupUsers extends TableImpl<UserGroupUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.user_group_users</code>
     */
    public static final UserGroupUsers USER_GROUP_USERS = new UserGroupUsers();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<UserGroupUsersRecord> getRecordType() {
        return UserGroupUsersRecord.class;
    }

    /**
     * The column <code>public.user_group_users.user_group_id</code>.
     */
    public final TableField<UserGroupUsersRecord, String> USER_GROUP_ID = createField(DSL.name("user_group_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>public.user_group_users.user_id</code>.
     */
    public final TableField<UserGroupUsersRecord, String> USER_ID = createField(DSL.name("user_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    private UserGroupUsers(Name alias, Table<UserGroupUsersRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private UserGroupUsers(Name alias, Table<UserGroupUsersRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.user_group_users</code> table reference
     */
    public UserGroupUsers(String alias) {
        this(DSL.name(alias), USER_GROUP_USERS);
    }

    /**
     * Create an aliased <code>public.user_group_users</code> table reference
     */
    public UserGroupUsers(Name alias) {
        this(alias, USER_GROUP_USERS);
    }

    /**
     * Create a <code>public.user_group_users</code> table reference
     */
    public UserGroupUsers() {
        this(DSL.name("user_group_users"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<UserGroupUsersRecord> getPrimaryKey() {
        return Keys.PK_USER_GROUP_USERS;
    }

    @Override
    public List<ForeignKey<UserGroupUsersRecord, ?>> getReferences() {
        return Arrays.asList(Keys.USER_GROUP_USERS__FK_USEGROUSE_ON_USER, Keys.USER_GROUP_USERS__FK_USEGROUSE_ON_USER_GROUP);
    }

    @Override
    public UserGroupUsers as(String alias) {
        return new UserGroupUsers(DSL.name(alias), this);
    }

    @Override
    public UserGroupUsers as(Name alias) {
        return new UserGroupUsers(alias, this);
    }

    @Override
    public UserGroupUsers as(Table<?> alias) {
        return new UserGroupUsers(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public UserGroupUsers rename(String name) {
        return new UserGroupUsers(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserGroupUsers rename(Name name) {
        return new UserGroupUsers(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public UserGroupUsers rename(Table<?> name) {
        return new UserGroupUsers(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserGroupUsers where(Condition condition) {
        return new UserGroupUsers(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserGroupUsers where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserGroupUsers where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserGroupUsers where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserGroupUsers where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserGroupUsers where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserGroupUsers where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public UserGroupUsers where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserGroupUsers whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public UserGroupUsers whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
