/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_;


import org.nmcpye.datarun.jooq.public_.tables.Activity;
import org.nmcpye.datarun.jooq.public_.tables.AppUser;
import org.nmcpye.datarun.jooq.public_.tables.Assignment;
import org.nmcpye.datarun.jooq.public_.tables.AssignmentMember;
import org.nmcpye.datarun.jooq.public_.tables.AssignmentPartyBinding;
import org.nmcpye.datarun.jooq.public_.tables.DataTemplate;
import org.nmcpye.datarun.jooq.public_.tables.DataTemplateVersion;
import org.nmcpye.datarun.jooq.public_.tables.OrgUnit;
import org.nmcpye.datarun.jooq.public_.tables.Party;
import org.nmcpye.datarun.jooq.public_.tables.PartySet;
import org.nmcpye.datarun.jooq.public_.tables.PartySetMember;
import org.nmcpye.datarun.jooq.public_.tables.PartyTag;
import org.nmcpye.datarun.jooq.public_.tables.Project;
import org.nmcpye.datarun.jooq.public_.tables.Team;
import org.nmcpye.datarun.jooq.public_.tables.TeamUser;
import org.nmcpye.datarun.jooq.public_.tables.UserExecutionContext;
import org.nmcpye.datarun.jooq.public_.tables.UserGroup;
import org.nmcpye.datarun.jooq.public_.tables.UserGroupUsers;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>public.activity</code>.
     */
    public static final Activity ACTIVITY = Activity.ACTIVITY;

    /**
     * The table <code>public.app_user</code>.
     */
    public static final AppUser APP_USER = AppUser.APP_USER;

    /**
     * The table <code>public.assignment</code>.
     */
    public static final Assignment ASSIGNMENT = Assignment.ASSIGNMENT;

    /**
     * The table <code>public.assignment_member</code>.
     */
    public static final AssignmentMember ASSIGNMENT_MEMBER = AssignmentMember.ASSIGNMENT_MEMBER;

    /**
     * The table <code>public.assignment_party_binding</code>.
     */
    public static final AssignmentPartyBinding ASSIGNMENT_PARTY_BINDING = AssignmentPartyBinding.ASSIGNMENT_PARTY_BINDING;

    /**
     * The table <code>public.data_template</code>.
     */
    public static final DataTemplate DATA_TEMPLATE = DataTemplate.DATA_TEMPLATE;

    /**
     * The table <code>public.data_template_version</code>.
     */
    public static final DataTemplateVersion DATA_TEMPLATE_VERSION = DataTemplateVersion.DATA_TEMPLATE_VERSION;

    /**
     * The table <code>public.org_unit</code>.
     */
    public static final OrgUnit ORG_UNIT = OrgUnit.ORG_UNIT;

    /**
     * The table <code>public.party</code>.
     */
    public static final Party PARTY = Party.PARTY;

    /**
     * The table <code>public.party_set</code>.
     */
    public static final PartySet PARTY_SET = PartySet.PARTY_SET;

    /**
     * The table <code>public.party_set_member</code>.
     */
    public static final PartySetMember PARTY_SET_MEMBER = PartySetMember.PARTY_SET_MEMBER;

    /**
     * The table <code>public.party_tag</code>.
     */
    public static final PartyTag PARTY_TAG = PartyTag.PARTY_TAG;

    /**
     * The table <code>public.project</code>.
     */
    public static final Project PROJECT = Project.PROJECT;

    /**
     * The table <code>public.team</code>.
     */
    public static final Team TEAM = Team.TEAM;

    /**
     * The table <code>public.team_user</code>.
     */
    public static final TeamUser TEAM_USER = TeamUser.TEAM_USER;

    /**
     * The table <code>public.user_execution_context</code>.
     */
    public static final UserExecutionContext USER_EXECUTION_CONTEXT = UserExecutionContext.USER_EXECUTION_CONTEXT;

    /**
     * The table <code>public.user_group</code>.
     */
    public static final UserGroup USER_GROUP = UserGroup.USER_GROUP;

    /**
     * The table <code>public.user_group_users</code>.
     */
    public static final UserGroupUsers USER_GROUP_USERS = UserGroupUsers.USER_GROUP_USERS;
}
