package org.nmcpye.datarun.party.service;

import jakarta.transaction.Transactional;
import lombok.Builder;
import lombok.Data;
import lombok.RequiredArgsConstructor;
import lombok.experimental.Accessors;
import lombok.extern.slf4j.Slf4j;
import org.nmcpye.datarun.party.entities.Party;
import org.nmcpye.datarun.party.entities.Party.PartyType;
import org.nmcpye.datarun.party.entities.Party.SourceType;
import org.nmcpye.datarun.party.repository.PartyRepository;
import org.springframework.stereotype.Service;

import java.time.Instant;
import java.util.List;
import java.util.Map;
import java.util.Objects;

@Service
@RequiredArgsConstructor
@Slf4j
public class PartySyncService {

    private final PartyRepository partyRepo;

    @Data
    @Builder
    @Accessors(fluent = true)
    public static class ToSyncParty {
        private String id;
        private String uid;
        private String code;
        private SourceType sourceType;
        private String name;
        private Map<String, String> label;
        private String parentId;
        private List<String> tags;
        private Map<String, Object> meta;
    }

    /**
     * Generic upsert method.
     * We use the ID as the source of truth. If it exists, we update label/meta.
     */
    @Transactional
    public void syncParty(ToSyncParty toSyncParty) {
        String partyParentId;
        if (toSyncParty.sourceType == SourceType.ORG_UNIT && toSyncParty.parentId != null) {
            final var partyParent = partyRepo.findBySourceId(toSyncParty.parentId)
                    .orElse(null);
            partyParentId = partyParent != null ? partyParent.getId() : null;
        } else {
            partyParentId = null;
        }

        partyRepo.findByUid(toSyncParty.uid).ifPresentOrElse(
                // Case A: Update existing
                existing -> {
                    boolean changed = !Objects.equals(existing.getParentId(), partyParentId)
                            || !Objects.equals(existing.getLabel(), toSyncParty.label)
                            || !Objects.equals(existing.getName(), toSyncParty.name)
                            || !Objects.equals(existing.getCode(), toSyncParty.code);
                    log.debug("Updating Party index: {} ({})", toSyncParty.name, toSyncParty.uid);
                    if (changed) {
                        existing.setName(toSyncParty.name);
                        existing.setCode(toSyncParty.code);
                        existing.setLabel(toSyncParty.label);
                        existing.setType(PartyType.INTERNAL); // we'll focus on internal for now
                        existing.setSourceType(toSyncParty.sourceType);
                        existing.setParentId(partyParentId);
                        // existing.setTags(toSyncParty.tags); // because they are frequently created, i
                        // am thinking of moving them
                        // existing.setProperties(toSyncParty.meta); // because they are frequently
                        // created, i am thinking of moving them
                        existing.setLastModifiedDate(Instant.now());
                        log.debug("Updated Party index: {} ({})", toSyncParty.name, toSyncParty.uid);
                    }
                },
                // Case B: Create new
                () -> {
                    Party newParty = Party.builder()
                            // No longer generating UUID for the ID - it will be generated by
                            // CodeGenerator/ULID automatically or we can set it explicitly. We'll let
                            // JpaIdentifiableObject auto-generate the `id`.
                            .code(toSyncParty.code)
                            .type(PartyType.INTERNAL)
                            .name(toSyncParty.name)
                            .parentId(partyParentId)
                            .sourceType(toSyncParty.sourceType)
                            .sourceId(toSyncParty.id)
                            .build();
                    newParty.setUid(toSyncParty.uid); // Keeps the same UID as the source
                    newParty.setLabel(toSyncParty.label);

                    partyRepo.persistAndFlush(newParty);

                    log.info("Indexed new Party: {} ({})", toSyncParty.name, toSyncParty.uid);
                });
    }

    public void updateUserPartyTags(String s) {
        // not implemented yet
    }
}
