/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.Activity;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ActivityRecord extends UpdatableRecordImpl<ActivityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.activity.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.activity.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.activity.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.activity.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.activity.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.activity.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.activity.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.activity.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.activity.start_date</code>.
     */
    public void setStartDate(LocalDateTime value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.activity.start_date</code>.
     */
    public LocalDateTime getStartDate() {
        return (LocalDateTime) get(4);
    }

    /**
     * Setter for <code>public.activity.end_date</code>.
     */
    public void setEndDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.activity.end_date</code>.
     */
    public LocalDateTime getEndDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.activity.disabled</code>.
     */
    public void setDisabled(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.activity.disabled</code>.
     */
    public Boolean getDisabled() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.activity.project_id</code>.
     */
    public void setProjectId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.activity.project_id</code>.
     */
    public String getProjectId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.activity.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.activity.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(8);
    }

    /**
     * Setter for <code>public.activity.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.activity.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.activity.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.activity.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.activity.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.activity.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.activity.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.activity.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(12);
    }

    /**
     * Setter for <code>public.activity.properties_map</code>.
     */
    public void setPropertiesMap(JSONB value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.activity.properties_map</code>.
     */
    public JSONB getPropertiesMap() {
        return (JSONB) get(13);
    }

    /**
     * Setter for <code>public.activity.planned_duration_days</code>. Optional
     * duration in days.
     */
    public void setPlannedDurationDays(Integer value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.activity.planned_duration_days</code>. Optional
     * duration in days.
     */
    public Integer getPlannedDurationDays() {
        return (Integer) get(14);
    }

    /**
     * Setter for <code>public.activity.valid_from</code>. Optional valid from
     * datetime.
     */
    public void setValidFrom(LocalDateTime value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.activity.valid_from</code>. Optional valid from
     * datetime.
     */
    public LocalDateTime getValidFrom() {
        return (LocalDateTime) get(15);
    }

    /**
     * Setter for <code>public.activity.valid_to</code>. Optional valid to
     * datetime.
     */
    public void setValidTo(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.activity.valid_to</code>. Optional valid to
     * datetime.
     */
    public LocalDateTime getValidTo() {
        return (LocalDateTime) get(16);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ActivityRecord
     */
    public ActivityRecord() {
        super(Activity.ACTIVITY);
    }

    /**
     * Create a detached, initialised ActivityRecord
     */
    public ActivityRecord(String id, String uid, String code, String name, LocalDateTime startDate, LocalDateTime endDate, Boolean disabled, String projectId, JSONB translations, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate, JSONB propertiesMap, Integer plannedDurationDays, LocalDateTime validFrom, LocalDateTime validTo) {
        super(Activity.ACTIVITY);

        setId(id);
        setUid(uid);
        setCode(code);
        setName(name);
        setStartDate(startDate);
        setEndDate(endDate);
        setDisabled(disabled);
        setProjectId(projectId);
        setTranslations(translations);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        setPropertiesMap(propertiesMap);
        setPlannedDurationDays(plannedDurationDays);
        setValidFrom(validFrom);
        setValidTo(validTo);
        resetChangedOnNotNull();
    }
}
