/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.AppUser;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AppUserRecord extends UpdatableRecordImpl<AppUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.app_user.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.app_user.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.app_user.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.app_user.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.app_user.mobile</code>.
     */
    public void setMobile(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.app_user.mobile</code>.
     */
    public String getMobile() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.app_user.login</code>.
     */
    public void setLogin(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.app_user.login</code>.
     */
    public String getLogin() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.app_user.password_hash</code>.
     */
    public void setPasswordHash(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.app_user.password_hash</code>.
     */
    public String getPasswordHash() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.app_user.first_name</code>.
     */
    public void setFirstName(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.app_user.first_name</code>.
     */
    public String getFirstName() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.app_user.last_name</code>.
     */
    public void setLastName(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.app_user.last_name</code>.
     */
    public String getLastName() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.app_user.email</code>.
     */
    public void setEmail(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.app_user.email</code>.
     */
    public String getEmail() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.app_user.activated</code>.
     */
    public void setActivated(Boolean value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.app_user.activated</code>.
     */
    public Boolean getActivated() {
        return (Boolean) get(8);
    }

    /**
     * Setter for <code>public.app_user.lang_key</code>.
     */
    public void setLangKey(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.app_user.lang_key</code>.
     */
    public String getLangKey() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.app_user.image_url</code>.
     */
    public void setImageUrl(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.app_user.image_url</code>.
     */
    public String getImageUrl() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.app_user.activation_key</code>.
     */
    public void setActivationKey(String value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.app_user.activation_key</code>.
     */
    public String getActivationKey() {
        return (String) get(11);
    }

    /**
     * Setter for <code>public.app_user.reset_key</code>.
     */
    public void setResetKey(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.app_user.reset_key</code>.
     */
    public String getResetKey() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.app_user.reset_date</code>.
     */
    public void setResetDate(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.app_user.reset_date</code>.
     */
    public LocalDateTime getResetDate() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.app_user.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.app_user.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(14);
    }

    /**
     * Setter for <code>public.app_user.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.app_user.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(15);
    }

    /**
     * Setter for <code>public.app_user.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.app_user.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(16);
    }

    /**
     * Setter for <code>public.app_user.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.app_user.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(17);
    }

    /**
     * Setter for <code>public.app_user.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.app_user.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(18);
    }

    /**
     * Setter for <code>public.app_user.properties_map</code>.
     */
    public void setPropertiesMap(JSONB value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.app_user.properties_map</code>.
     */
    public JSONB getPropertiesMap() {
        return (JSONB) get(19);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AppUserRecord
     */
    public AppUserRecord() {
        super(AppUser.APP_USER);
    }

    /**
     * Create a detached, initialised AppUserRecord
     */
    public AppUserRecord(String id, String uid, String mobile, String login, String passwordHash, String firstName, String lastName, String email, Boolean activated, String langKey, String imageUrl, String activationKey, String resetKey, LocalDateTime resetDate, JSONB translations, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate, JSONB propertiesMap) {
        super(AppUser.APP_USER);

        setId(id);
        setUid(uid);
        setMobile(mobile);
        setLogin(login);
        setPasswordHash(passwordHash);
        setFirstName(firstName);
        setLastName(lastName);
        setEmail(email);
        setActivated(activated);
        setLangKey(langKey);
        setImageUrl(imageUrl);
        setActivationKey(activationKey);
        setResetKey(resetKey);
        setResetDate(resetDate);
        setTranslations(translations);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        setPropertiesMap(propertiesMap);
        resetChangedOnNotNull();
    }
}
