/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.AssignmentPartyBinding;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignmentPartyBindingRecord extends UpdatableRecordImpl<AssignmentPartyBindingRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.assignment_party_binding.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.assignment_party_binding.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.assignment_party_binding.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.assignment_party_binding.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.assignment_party_binding.name</code>.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.assignment_party_binding.name</code>.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.assignment_party_binding.assignment_id</code>.
     */
    public void setAssignmentId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.assignment_party_binding.assignment_id</code>.
     */
    public String getAssignmentId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.assignment_party_binding.vocabulary_id</code>.
     */
    public void setVocabularyId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.assignment_party_binding.vocabulary_id</code>.
     */
    public String getVocabularyId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.assignment_party_binding.party_set_id</code>.
     */
    public void setPartySetId(UUID value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.assignment_party_binding.party_set_id</code>.
     */
    public UUID getPartySetId() {
        return (UUID) get(5);
    }

    /**
     * Setter for <code>public.assignment_party_binding.principal_type</code>.
     */
    public void setPrincipalType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.assignment_party_binding.principal_type</code>.
     */
    public String getPrincipalType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.assignment_party_binding.principal_id</code>.
     */
    public void setPrincipalId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.assignment_party_binding.principal_id</code>.
     */
    public String getPrincipalId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.assignment_party_binding.combine_mode</code>.
     */
    public void setCombineMode(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.assignment_party_binding.combine_mode</code>.
     */
    public String getCombineMode() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.assignment_party_binding.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.assignment_party_binding.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.assignment_party_binding.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.assignment_party_binding.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(10);
    }

    /**
     * Setter for
     * <code>public.assignment_party_binding.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for
     * <code>public.assignment_party_binding.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.assignment_party_binding.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.assignment_party_binding.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssignmentPartyBindingRecord
     */
    public AssignmentPartyBindingRecord() {
        super(AssignmentPartyBinding.ASSIGNMENT_PARTY_BINDING);
    }

    /**
     * Create a detached, initialised AssignmentPartyBindingRecord
     */
    public AssignmentPartyBindingRecord(UUID id, String uid, String name, String assignmentId, String vocabularyId, UUID partySetId, String principalType, String principalId, String combineMode, LocalDateTime createdDate, String createdBy, LocalDateTime lastModifiedDate, String lastModifiedBy) {
        super(AssignmentPartyBinding.ASSIGNMENT_PARTY_BINDING);

        setId(id);
        setUid(uid);
        setName(name);
        setAssignmentId(assignmentId);
        setVocabularyId(vocabularyId);
        setPartySetId(partySetId);
        setPrincipalType(principalType);
        setPrincipalId(principalId);
        setCombineMode(combineMode);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        resetChangedOnNotNull();
    }
}
