/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.AssignmentMember;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignmentMemberRecord extends UpdatableRecordImpl<AssignmentMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.assignment_member.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.assignment_member.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.assignment_member.assignment_id</code>.
     */
    public void setAssignmentId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.assignment_member.assignment_id</code>.
     */
    public String getAssignmentId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.assignment_member.member_type</code>.
     */
    public void setMemberType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.assignment_member.member_type</code>.
     */
    public String getMemberType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.assignment_member.member_id</code>.
     */
    public void setMemberId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.assignment_member.member_id</code>.
     */
    public String getMemberId() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.assignment_member.role</code>.
     */
    public void setRole(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.assignment_member.role</code>.
     */
    public String getRole() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.assignment_member.valid_from</code>.
     */
    public void setValidFrom(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.assignment_member.valid_from</code>.
     */
    public LocalDateTime getValidFrom() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.assignment_member.valid_to</code>.
     */
    public void setValidTo(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.assignment_member.valid_to</code>.
     */
    public LocalDateTime getValidTo() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>public.assignment_member.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.assignment_member.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.assignment_member.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.assignment_member.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.assignment_member.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.assignment_member.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.assignment_member.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.assignment_member.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssignmentMemberRecord
     */
    public AssignmentMemberRecord() {
        super(AssignmentMember.ASSIGNMENT_MEMBER);
    }

    /**
     * Create a detached, initialised AssignmentMemberRecord
     */
    public AssignmentMemberRecord(Long id, String assignmentId, String memberType, String memberId, String role, LocalDateTime validFrom, LocalDateTime validTo, LocalDateTime createdDate, String createdBy, LocalDateTime lastModifiedDate, String lastModifiedBy) {
        super(AssignmentMember.ASSIGNMENT_MEMBER);

        setId(id);
        setAssignmentId(assignmentId);
        setMemberType(memberType);
        setMemberId(memberId);
        setRole(role);
        setValidFrom(validFrom);
        setValidTo(validTo);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        resetChangedOnNotNull();
    }
}
