/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.Assignment;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AssignmentRecord extends UpdatableRecordImpl<AssignmentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.assignment.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.assignment.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.assignment.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.assignment.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.assignment.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.assignment.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(2);
    }

    /**
     * Setter for <code>public.assignment.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.assignment.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>public.assignment.activity_id</code>.
     */
    public void setActivityId(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.assignment.activity_id</code>.
     */
    public String getActivityId() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.assignment.start_day</code>.
     */
    public void setStartDay(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.assignment.start_day</code>.
     */
    public Integer getStartDay() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.assignment.org_unit_id</code>.
     */
    public void setOrgUnitId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.assignment.org_unit_id</code>.
     */
    public String getOrgUnitId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.assignment.team_id</code>.
     */
    public void setTeamId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.assignment.team_id</code>.
     */
    public String getTeamId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.assignment.path</code>.
     */
    public void setPath(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.assignment.path</code>.
     */
    public String getPath() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.assignment.level</code>.
     */
    public void setLevel(Integer value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.assignment.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(9);
    }

    /**
     * Setter for <code>public.assignment.parent_id</code>.
     */
    public void setParentId(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.assignment.parent_id</code>.
     */
    public String getParentId() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.assignment.forms</code>.
     */
    public void setForms(JSONB value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.assignment.forms</code>.
     */
    public JSONB getForms() {
        return (JSONB) get(11);
    }

    /**
     * Setter for <code>public.assignment.allocated_resources</code>.
     */
    public void setAllocatedResources(JSONB value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.assignment.allocated_resources</code>.
     */
    public JSONB getAllocatedResources() {
        return (JSONB) get(12);
    }

    /**
     * Setter for <code>public.assignment.status</code>.
     */
    public void setStatus(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.assignment.status</code>.
     */
    public String getStatus() {
        return (String) get(13);
    }

    /**
     * Setter for <code>public.assignment.last_submitted_by</code>.
     */
    public void setLastSubmittedBy(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.assignment.last_submitted_by</code>.
     */
    public String getLastSubmittedBy() {
        return (String) get(14);
    }

    /**
     * Setter for <code>public.assignment.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(15, value);
    }

    /**
     * Getter for <code>public.assignment.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(15);
    }

    /**
     * Setter for <code>public.assignment.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(16, value);
    }

    /**
     * Getter for <code>public.assignment.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(16);
    }

    /**
     * Setter for <code>public.assignment.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(17, value);
    }

    /**
     * Getter for <code>public.assignment.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(17);
    }

    /**
     * Setter for <code>public.assignment.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(18, value);
    }

    /**
     * Getter for <code>public.assignment.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(18);
    }

    /**
     * Setter for <code>public.assignment.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(19, value);
    }

    /**
     * Getter for <code>public.assignment.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(19);
    }

    /**
     * Setter for <code>public.assignment.properties_map</code>.
     */
    public void setPropertiesMap(JSONB value) {
        set(20, value);
    }

    /**
     * Getter for <code>public.assignment.properties_map</code>.
     */
    public JSONB getPropertiesMap() {
        return (JSONB) get(20);
    }

    /**
     * Setter for <code>public.assignment.default_party_set_id</code>.
     */
    public void setDefaultPartySetId(UUID value) {
        set(21, value);
    }

    /**
     * Getter for <code>public.assignment.default_party_set_id</code>.
     */
    public UUID getDefaultPartySetId() {
        return (UUID) get(21);
    }

    /**
     * Setter for <code>public.assignment.code</code>.
     */
    public void setCode(String value) {
        set(22, value);
    }

    /**
     * Getter for <code>public.assignment.code</code>.
     */
    public String getCode() {
        return (String) get(22);
    }

    /**
     * Setter for <code>public.assignment.name</code>.
     */
    public void setName(String value) {
        set(23, value);
    }

    /**
     * Getter for <code>public.assignment.name</code>.
     */
    public String getName() {
        return (String) get(23);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AssignmentRecord
     */
    public AssignmentRecord() {
        super(Assignment.ASSIGNMENT);
    }

    /**
     * Create a detached, initialised AssignmentRecord
     */
    public AssignmentRecord(String id, String uid, Boolean deleted, LocalDateTime deletedAt, String activityId, Integer startDay, String orgUnitId, String teamId, String path, Integer level, String parentId, JSONB forms, JSONB allocatedResources, String status, String lastSubmittedBy, JSONB translations, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate, JSONB propertiesMap, UUID defaultPartySetId, String code, String name) {
        super(Assignment.ASSIGNMENT);

        setId(id);
        setUid(uid);
        setDeleted(deleted);
        setDeletedAt(deletedAt);
        setActivityId(activityId);
        setStartDay(startDay);
        setOrgUnitId(orgUnitId);
        setTeamId(teamId);
        setPath(path);
        setLevel(level);
        setParentId(parentId);
        setForms(forms);
        setAllocatedResources(allocatedResources);
        setStatus(status);
        setLastSubmittedBy(lastSubmittedBy);
        setTranslations(translations);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        setPropertiesMap(propertiesMap);
        setDefaultPartySetId(defaultPartySetId);
        setCode(code);
        setName(name);
        resetChangedOnNotNull();
    }
}
