/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.DataTemplateVersion;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataTemplateVersionRecord extends UpdatableRecordImpl<DataTemplateVersionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.data_template_version.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.data_template_version.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.data_template_version.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.data_template_version.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.data_template_version.template_uid</code>.
     */
    public void setTemplateUid(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.data_template_version.template_uid</code>.
     */
    public String getTemplateUid() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.data_template_version.version_number</code>.
     */
    public void setVersionNumber(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.data_template_version.version_number</code>.
     */
    public Integer getVersionNumber() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>public.data_template_version.release_notes</code>.
     */
    public void setReleaseNotes(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.data_template_version.release_notes</code>.
     */
    public String getReleaseNotes() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.data_template_version.fields</code>.
     */
    public void setFields(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.data_template_version.fields</code>.
     */
    public JSONB getFields() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.data_template_version.sections</code>.
     */
    public void setSections(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.data_template_version.sections</code>.
     */
    public JSONB getSections() {
        return (JSONB) get(6);
    }

    /**
     * Setter for <code>public.data_template_version.data_template_id</code>.
     */
    public void setDataTemplateId(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.data_template_version.data_template_id</code>.
     */
    public String getDataTemplateId() {
        return (String) get(7);
    }

    /**
     * Setter for <code>public.data_template_version.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.data_template_version.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.data_template_version.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.data_template_version.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(9);
    }

    /**
     * Setter for <code>public.data_template_version.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.data_template_version.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(10);
    }

    /**
     * Setter for <code>public.data_template_version.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.data_template_version.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.data_template_version.options</code>.
     */
    public void setOptions(JSONB value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.data_template_version.options</code>.
     */
    public JSONB getOptions() {
        return (JSONB) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataTemplateVersionRecord
     */
    public DataTemplateVersionRecord() {
        super(DataTemplateVersion.DATA_TEMPLATE_VERSION);
    }

    /**
     * Create a detached, initialised DataTemplateVersionRecord
     */
    public DataTemplateVersionRecord(String id, String uid, String templateUid, Integer versionNumber, String releaseNotes, JSONB fields, JSONB sections, String dataTemplateId, String createdBy, String lastModifiedBy, LocalDateTime createdDate, LocalDateTime lastModifiedDate, JSONB options) {
        super(DataTemplateVersion.DATA_TEMPLATE_VERSION);

        setId(id);
        setUid(uid);
        setTemplateUid(templateUid);
        setVersionNumber(versionNumber);
        setReleaseNotes(releaseNotes);
        setFields(fields);
        setSections(sections);
        setDataTemplateId(dataTemplateId);
        setCreatedBy(createdBy);
        setLastModifiedBy(lastModifiedBy);
        setCreatedDate(createdDate);
        setLastModifiedDate(lastModifiedDate);
        setOptions(options);
        resetChangedOnNotNull();
    }
}
