/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.DataTemplate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class DataTemplateRecord extends UpdatableRecordImpl<DataTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.data_template.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.data_template.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.data_template.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.data_template.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.data_template.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.data_template.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.data_template.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.data_template.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.data_template.version_uid</code>.
     */
    public void setVersionUid(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.data_template.version_uid</code>.
     */
    public String getVersionUid() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.data_template.version_number</code>.
     */
    public void setVersionNumber(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.data_template.version_number</code>.
     */
    public Integer getVersionNumber() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.data_template.deleted</code>.
     */
    public void setDeleted(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.data_template.deleted</code>.
     */
    public Boolean getDeleted() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.data_template.deleted_at</code>.
     */
    public void setDeletedAt(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.data_template.deleted_at</code>.
     */
    public LocalDateTime getDeletedAt() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.data_template.description</code>.
     */
    public void setDescription(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.data_template.description</code>.
     */
    public String getDescription() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.data_template.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.data_template.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(9);
    }

    /**
     * Setter for <code>public.data_template.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.data_template.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.data_template.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.data_template.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.data_template.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.data_template.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(12);
    }

    /**
     * Setter for <code>public.data_template.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(13, value);
    }

    /**
     * Getter for <code>public.data_template.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(13);
    }

    /**
     * Setter for <code>public.data_template.properties_map</code>.
     */
    public void setPropertiesMap(JSONB value) {
        set(14, value);
    }

    /**
     * Getter for <code>public.data_template.properties_map</code>.
     */
    public JSONB getPropertiesMap() {
        return (JSONB) get(14);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DataTemplateRecord
     */
    public DataTemplateRecord() {
        super(DataTemplate.DATA_TEMPLATE);
    }

    /**
     * Create a detached, initialised DataTemplateRecord
     */
    public DataTemplateRecord(String id, String uid, String code, String name, String versionUid, Integer versionNumber, Boolean deleted, LocalDateTime deletedAt, String description, JSONB translations, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate, JSONB propertiesMap) {
        super(DataTemplate.DATA_TEMPLATE);

        setId(id);
        setUid(uid);
        setCode(code);
        setName(name);
        setVersionUid(versionUid);
        setVersionNumber(versionNumber);
        setDeleted(deleted);
        setDeletedAt(deletedAt);
        setDescription(description);
        setTranslations(translations);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        setPropertiesMap(propertiesMap);
        resetChangedOnNotNull();
    }
}
