/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.OrgUnit;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OrgUnitRecord extends UpdatableRecordImpl<OrgUnitRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.org_unit.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.org_unit.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.org_unit.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.org_unit.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.org_unit.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.org_unit.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.org_unit.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.org_unit.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.org_unit.path</code>.
     */
    public void setPath(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.org_unit.path</code>.
     */
    public String getPath() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.org_unit.level</code>.
     */
    public void setLevel(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.org_unit.level</code>.
     */
    public Integer getLevel() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>public.org_unit.parent_id</code>.
     */
    public void setParentId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.org_unit.parent_id</code>.
     */
    public String getParentId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.org_unit.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.org_unit.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(7);
    }

    /**
     * Setter for <code>public.org_unit.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.org_unit.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.org_unit.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.org_unit.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.org_unit.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.org_unit.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.org_unit.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.org_unit.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(11);
    }

    /**
     * Setter for <code>public.org_unit.properties_map</code>.
     */
    public void setPropertiesMap(JSONB value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.org_unit.properties_map</code>.
     */
    public JSONB getPropertiesMap() {
        return (JSONB) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OrgUnitRecord
     */
    public OrgUnitRecord() {
        super(OrgUnit.ORG_UNIT);
    }

    /**
     * Create a detached, initialised OrgUnitRecord
     */
    public OrgUnitRecord(String id, String uid, String code, String name, String path, Integer level, String parentId, JSONB translations, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate, JSONB propertiesMap) {
        super(OrgUnit.ORG_UNIT);

        setId(id);
        setUid(uid);
        setCode(code);
        setName(name);
        setPath(path);
        setLevel(level);
        setParentId(parentId);
        setTranslations(translations);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        setPropertiesMap(propertiesMap);
        resetChangedOnNotNull();
    }
}
