/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.PartySet;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartySetRecord extends UpdatableRecordImpl<PartySetRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.party_set.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.party_set.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.party_set.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.party_set.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.party_set.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.party_set.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.party_set.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.party_set.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.party_set.kind</code>.
     */
    public void setKind(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.party_set.kind</code>.
     */
    public String getKind() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.party_set.spec</code>.
     */
    public void setSpec(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.party_set.spec</code>.
     */
    public JSONB getSpec() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.party_set.is_materialized</code>.
     */
    public void setIsMaterialized(Boolean value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.party_set.is_materialized</code>.
     */
    public Boolean getIsMaterialized() {
        return (Boolean) get(6);
    }

    /**
     * Setter for <code>public.party_set.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.party_set.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.party_set.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.party_set.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.party_set.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.party_set.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.party_set.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.party_set.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.party_set.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.party_set.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(11);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PartySetRecord
     */
    public PartySetRecord() {
        super(PartySet.PARTY_SET);
    }

    /**
     * Create a detached, initialised PartySetRecord
     */
    public PartySetRecord(UUID id, String uid, String code, String name, String kind, JSONB spec, Boolean isMaterialized, LocalDateTime createdDate, String createdBy, LocalDateTime lastModifiedDate, String lastModifiedBy, JSONB translations) {
        super(PartySet.PARTY_SET);

        setId(id);
        setUid(uid);
        setCode(code);
        setName(name);
        setKind(kind);
        setSpec(spec);
        setIsMaterialized(isMaterialized);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setTranslations(translations);
        resetChangedOnNotNull();
    }
}
