/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.util.UUID;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.PartySetMember;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartySetMemberRecord extends UpdatableRecordImpl<PartySetMemberRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.party_set_member.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.party_set_member.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.party_set_member.party_set_id</code>.
     */
    public void setPartySetId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.party_set_member.party_set_id</code>.
     */
    public UUID getPartySetId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.party_set_member.party_id</code>.
     */
    public void setPartyId(UUID value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.party_set_member.party_id</code>.
     */
    public UUID getPartyId() {
        return (UUID) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PartySetMemberRecord
     */
    public PartySetMemberRecord() {
        super(PartySetMember.PARTY_SET_MEMBER);
    }

    /**
     * Create a detached, initialised PartySetMemberRecord
     */
    public PartySetMemberRecord(Long id, UUID partySetId, UUID partyId) {
        super(PartySetMember.PARTY_SET_MEMBER);

        setId(id);
        setPartySetId(partySetId);
        setPartyId(partyId);
        resetChangedOnNotNull();
    }
}
