/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.Party;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartyRecord extends UpdatableRecordImpl<PartyRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.party.id</code>.
     */
    public void setId(UUID value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.party.id</code>.
     */
    public UUID getId() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>public.party.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.party.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.party.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.party.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.party.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.party.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.party.type</code>.
     */
    public void setType(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.party.type</code>.
     */
    public String getType() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.party.source_type</code>.
     */
    public void setSourceType(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.party.source_type</code>.
     */
    public String getSourceType() {
        return (String) get(5);
    }

    /**
     * Setter for <code>public.party.source_id</code>.
     */
    public void setSourceId(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.party.source_id</code>.
     */
    public String getSourceId() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.party.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.party.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.party.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.party.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.party.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.party.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.party.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.party.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(10);
    }

    /**
     * Setter for <code>public.party.parent_id</code>.
     */
    public void setParentId(UUID value) {
        set(11, value);
    }

    /**
     * Getter for <code>public.party.parent_id</code>.
     */
    public UUID getParentId() {
        return (UUID) get(11);
    }

    /**
     * Setter for <code>public.party.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(12, value);
    }

    /**
     * Getter for <code>public.party.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PartyRecord
     */
    public PartyRecord() {
        super(Party.PARTY);
    }

    /**
     * Create a detached, initialised PartyRecord
     */
    public PartyRecord(UUID id, String uid, String code, String name, String type, String sourceType, String sourceId, LocalDateTime createdDate, String createdBy, LocalDateTime lastModifiedDate, String lastModifiedBy, UUID parentId, JSONB translations) {
        super(Party.PARTY);

        setId(id);
        setUid(uid);
        setCode(code);
        setName(name);
        setType(type);
        setSourceType(sourceType);
        setSourceId(sourceId);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        setLastModifiedDate(lastModifiedDate);
        setLastModifiedBy(lastModifiedBy);
        setParentId(parentId);
        setTranslations(translations);
        resetChangedOnNotNull();
    }
}
