/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;
import java.util.UUID;

import org.jooq.JSONB;
import org.jooq.Record3;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.PartyTag;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PartyTagRecord extends UpdatableRecordImpl<PartyTagRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.party_tag.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.party_tag.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.party_tag.party_id</code>.
     */
    public void setPartyId(UUID value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.party_tag.party_id</code>.
     */
    public UUID getPartyId() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>public.party_tag.tag_key</code>.
     */
    public void setTagKey(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.party_tag.tag_key</code>.
     */
    public String getTagKey() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.party_tag.tag_value</code>.
     */
    public void setTagValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.party_tag.tag_value</code>.
     */
    public String getTagValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.party_tag.meta</code>.
     */
    public void setMeta(JSONB value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.party_tag.meta</code>.
     */
    public JSONB getMeta() {
        return (JSONB) get(4);
    }

    /**
     * Setter for <code>public.party_tag.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.party_tag.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.party_tag.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.party_tag.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record3<Long, UUID, String> key() {
        return (Record3) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PartyTagRecord
     */
    public PartyTagRecord() {
        super(PartyTag.PARTY_TAG);
    }

    /**
     * Create a detached, initialised PartyTagRecord
     */
    public PartyTagRecord(Long id, UUID partyId, String tagKey, String tagValue, JSONB meta, LocalDateTime createdDate, String createdBy) {
        super(PartyTag.PARTY_TAG);

        setId(id);
        setPartyId(partyId);
        setTagKey(tagKey);
        setTagValue(tagValue);
        setMeta(meta);
        setCreatedDate(createdDate);
        setCreatedBy(createdBy);
        resetChangedOnNotNull();
    }
}
