/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.Project;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProjectRecord extends UpdatableRecordImpl<ProjectRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.project.id</code>.
     */
    public void setId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.project.id</code>.
     */
    public String getId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.project.uid</code>.
     */
    public void setUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.project.uid</code>.
     */
    public String getUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.project.code</code>.
     */
    public void setCode(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.project.code</code>.
     */
    public String getCode() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.project.name</code>.
     */
    public void setName(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.project.name</code>.
     */
    public String getName() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.project.disabled</code>.
     */
    public void setDisabled(Boolean value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.project.disabled</code>.
     */
    public Boolean getDisabled() {
        return (Boolean) get(4);
    }

    /**
     * Setter for <code>public.project.translations</code>.
     */
    public void setTranslations(JSONB value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.project.translations</code>.
     */
    public JSONB getTranslations() {
        return (JSONB) get(5);
    }

    /**
     * Setter for <code>public.project.created_by</code>.
     */
    public void setCreatedBy(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.project.created_by</code>.
     */
    public String getCreatedBy() {
        return (String) get(6);
    }

    /**
     * Setter for <code>public.project.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>public.project.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>public.project.last_modified_by</code>.
     */
    public void setLastModifiedBy(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>public.project.last_modified_by</code>.
     */
    public String getLastModifiedBy() {
        return (String) get(8);
    }

    /**
     * Setter for <code>public.project.last_modified_date</code>.
     */
    public void setLastModifiedDate(LocalDateTime value) {
        set(9, value);
    }

    /**
     * Getter for <code>public.project.last_modified_date</code>.
     */
    public LocalDateTime getLastModifiedDate() {
        return (LocalDateTime) get(9);
    }

    /**
     * Setter for <code>public.project.properties_map</code>.
     */
    public void setPropertiesMap(JSONB value) {
        set(10, value);
    }

    /**
     * Getter for <code>public.project.properties_map</code>.
     */
    public JSONB getPropertiesMap() {
        return (JSONB) get(10);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProjectRecord
     */
    public ProjectRecord() {
        super(Project.PROJECT);
    }

    /**
     * Create a detached, initialised ProjectRecord
     */
    public ProjectRecord(String id, String uid, String code, String name, Boolean disabled, JSONB translations, String createdBy, LocalDateTime createdDate, String lastModifiedBy, LocalDateTime lastModifiedDate, JSONB propertiesMap) {
        super(Project.PROJECT);

        setId(id);
        setUid(uid);
        setCode(code);
        setName(name);
        setDisabled(disabled);
        setTranslations(translations);
        setCreatedBy(createdBy);
        setCreatedDate(createdDate);
        setLastModifiedBy(lastModifiedBy);
        setLastModifiedDate(lastModifiedDate);
        setPropertiesMap(propertiesMap);
        resetChangedOnNotNull();
    }
}
