/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.TeamUser;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TeamUserRecord extends UpdatableRecordImpl<TeamUserRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.team_user.team_id</code>.
     */
    public void setTeamId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.team_user.team_id</code>.
     */
    public String getTeamId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.team_user.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.team_user.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TeamUserRecord
     */
    public TeamUserRecord() {
        super(TeamUser.TEAM_USER);
    }

    /**
     * Create a detached, initialised TeamUserRecord
     */
    public TeamUserRecord(String teamId, String userId) {
        super(TeamUser.TEAM_USER);

        setTeamId(teamId);
        setUserId(userId);
        resetChangedOnNotNull();
    }
}
