/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import java.time.LocalDateTime;

import org.jooq.JSONB;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.UserExecutionContext;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserExecutionContextRecord extends UpdatableRecordImpl<UserExecutionContextRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_execution_context.id</code>.
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_execution_context.id</code>.
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.user_execution_context.user_uid</code>.
     */
    public void setUserUid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_execution_context.user_uid</code>.
     */
    public String getUserUid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.user_execution_context.entity_type</code>.
     */
    public void setEntityType(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.user_execution_context.entity_type</code>.
     */
    public String getEntityType() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.user_execution_context.entity_uid</code>.
     */
    public void setEntityUid(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.user_execution_context.entity_uid</code>.
     */
    public String getEntityUid() {
        return (String) get(3);
    }

    /**
     * Setter for
     * <code>public.user_execution_context.resolved_permission</code>.
     */
    public void setResolvedPermission(String value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>public.user_execution_context.resolved_permission</code>.
     */
    public String getResolvedPermission() {
        return (String) get(4);
    }

    /**
     * Setter for <code>public.user_execution_context.created_date</code>.
     */
    public void setCreatedDate(LocalDateTime value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.user_execution_context.created_date</code>.
     */
    public LocalDateTime getCreatedDate() {
        return (LocalDateTime) get(5);
    }

    /**
     * Setter for <code>public.user_execution_context.provenance</code>.
     */
    public void setProvenance(JSONB value) {
        set(6, value);
    }

    /**
     * Getter for <code>public.user_execution_context.provenance</code>.
     */
    public JSONB getProvenance() {
        return (JSONB) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserExecutionContextRecord
     */
    public UserExecutionContextRecord() {
        super(UserExecutionContext.USER_EXECUTION_CONTEXT);
    }

    /**
     * Create a detached, initialised UserExecutionContextRecord
     */
    public UserExecutionContextRecord(Long id, String userUid, String entityType, String entityUid, String resolvedPermission, LocalDateTime createdDate, JSONB provenance) {
        super(UserExecutionContext.USER_EXECUTION_CONTEXT);

        setId(id);
        setUserUid(userUid);
        setEntityType(entityType);
        setEntityUid(entityUid);
        setResolvedPermission(resolvedPermission);
        setCreatedDate(createdDate);
        setProvenance(provenance);
        resetChangedOnNotNull();
    }
}
