/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.public_.tables.records;


import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;
import org.nmcpye.datarun.jooq.public_.tables.UserGroupUsers;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserGroupUsersRecord extends UpdatableRecordImpl<UserGroupUsersRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.user_group_users.user_group_id</code>.
     */
    public void setUserGroupId(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.user_group_users.user_group_id</code>.
     */
    public String getUserGroupId() {
        return (String) get(0);
    }

    /**
     * Setter for <code>public.user_group_users.user_id</code>.
     */
    public void setUserId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.user_group_users.user_id</code>.
     */
    public String getUserId() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached UserGroupUsersRecord
     */
    public UserGroupUsersRecord() {
        super(UserGroupUsers.USER_GROUP_USERS);
    }

    /**
     * Create a detached, initialised UserGroupUsersRecord
     */
    public UserGroupUsersRecord(String userGroupId, String userId) {
        super(UserGroupUsers.USER_GROUP_USERS);

        setUserGroupId(userGroupId);
        setUserId(userId);
        resetChangedOnNotNull();
    }
}
