/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.analytics;


import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;
import org.nmcpye.datarun.jooq.DefaultCatalog;
import org.nmcpye.datarun.jooq.analytics.tables.TallCanonical;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Analytics extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>analytics</code>
     */
    public static final Analytics ANALYTICS = new Analytics();

    /**
     * Canonical tall analytics table. instance_key =
     * COALESCE(repeat_instance_id, submission_uid) used for idempotency
     */
    public final TallCanonical TALL_CANONICAL = TallCanonical.TALL_CANONICAL;

    /**
     * No further instances allowed
     */
    private Analytics() {
        super("analytics", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            TallCanonical.TALL_CANONICAL
        );
    }
}
