/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.analytics;


import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.nmcpye.datarun.jooq.analytics.tables.TallCanonical;


/**
 * A class modelling indexes of tables in analytics.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index IDX_TALL_CANONICAL_PARENT_INSTANCE = Internal.createIndex(DSL.name("idx_tall_canonical_parent_instance"), TallCanonical.TALL_CANONICAL, new OrderField[] { TallCanonical.TALL_CANONICAL.PARENT_INSTANCE_ID }, false);
    public static final Index IDX_TALL_CANONICAL_REPEAT_INSTANCE = Internal.createIndex(DSL.name("idx_tall_canonical_repeat_instance"), TallCanonical.TALL_CANONICAL, new OrderField[] { TallCanonical.TALL_CANONICAL.REPEAT_INSTANCE_ID }, false);
    public static final Index IDX_TALL_CANONICAL_SUBMISSION_UID = Internal.createIndex(DSL.name("idx_tall_canonical_submission_uid"), TallCanonical.TALL_CANONICAL, new OrderField[] { TallCanonical.TALL_CANONICAL.SUBMISSION_UID }, false);
    public static final Index IDX_TALL_CANONICAL_TEMPLATE_ELEMENT = Internal.createIndex(DSL.name("idx_tall_canonical_template_element"), TallCanonical.TALL_CANONICAL, new OrderField[] { TallCanonical.TALL_CANONICAL.TEMPLATE_UID, TallCanonical.TALL_CANONICAL.CANONICAL_ELEMENT_ID }, false);
    public static final Index IDX_TALL_CANONICAL_TEMPLATE_VERSION_ELEMENT = Internal.createIndex(DSL.name("idx_tall_canonical_template_version_element"), TallCanonical.TALL_CANONICAL, new OrderField[] { TallCanonical.TALL_CANONICAL.TEMPLATE_VERSION_UID, TallCanonical.TALL_CANONICAL.CANONICAL_ELEMENT_ID }, false);
    public static final Index IDX_TALL_CANONICAL_UPDATED_AT = Internal.createIndex(DSL.name("idx_tall_canonical_updated_at"), TallCanonical.TALL_CANONICAL, new OrderField[] { TallCanonical.TALL_CANONICAL.UPDATED_AT }, false);
    public static final Index IDX_TALL_VALUE_REF_UID = Internal.createIndex(DSL.name("idx_tall_value_ref_uid"), TallCanonical.TALL_CANONICAL, new OrderField[] { TallCanonical.TALL_CANONICAL.VALUE_REF_UID }, false);
}
