/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.analytics;


import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.nmcpye.datarun.jooq.analytics.tables.TallCanonical;
import org.nmcpye.datarun.jooq.analytics.tables.records.TallCanonicalRecord;


/**
 * A class modelling foreign key relationships and constraints of tables in
 * analytics.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<TallCanonicalRecord> PK_TALL_CANONICAL = Internal.createUniqueKey(TallCanonical.TALL_CANONICAL, DSL.name("pk_tall_canonical"), new TableField[] { TallCanonical.TALL_CANONICAL.TALL_ID }, true);
    public static final UniqueKey<TallCanonicalRecord> UQ_TALL_INSTANCE_CANONICAL = Internal.createUniqueKey(TallCanonical.TALL_CANONICAL, DSL.name("uq_tall_instance_canonical"), new TableField[] { TallCanonical.TALL_CANONICAL.INSTANCE_KEY, TallCanonical.TALL_CANONICAL.CANONICAL_ELEMENT_ID }, true);
}
