/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.analytics;


import org.nmcpye.datarun.jooq.analytics.tables.TallCanonical;


/**
 * Convenience access to all tables in analytics.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * Canonical tall analytics table. instance_key =
     * COALESCE(repeat_instance_id, submission_uid) used for idempotency
     */
    public static final TallCanonical TALL_CANONICAL = TallCanonical.TALL_CANONICAL;
}
