/*
 * This file is generated by jOOQ.
 */
package org.nmcpye.datarun.jooq.analytics.tables;


import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Arrays;
import java.util.Collection;
import java.util.List;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.JSONB;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.nmcpye.datarun.jooq.analytics.Analytics;
import org.nmcpye.datarun.jooq.analytics.Indexes;
import org.nmcpye.datarun.jooq.analytics.Keys;
import org.nmcpye.datarun.jooq.analytics.tables.records.TallCanonicalRecord;


/**
 * Canonical tall analytics table. instance_key = COALESCE(repeat_instance_id,
 * submission_uid) used for idempotency
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TallCanonical extends TableImpl<TallCanonicalRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>analytics.tall_canonical</code>
     */
    public static final TallCanonical TALL_CANONICAL = new TallCanonical();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TallCanonicalRecord> getRecordType() {
        return TallCanonicalRecord.class;
    }

    /**
     * The column <code>analytics.tall_canonical.tall_id</code>.
     */
    public final TableField<TallCanonicalRecord, Long> TALL_ID = createField(DSL.name("tall_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>analytics.tall_canonical.outbox_id</code>.
     */
    public final TableField<TallCanonicalRecord, Long> OUTBOX_ID = createField(DSL.name("outbox_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>analytics.tall_canonical.ingest_id</code>.
     */
    public final TableField<TallCanonicalRecord, UUID> INGEST_ID = createField(DSL.name("ingest_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column
     * <code>analytics.tall_canonical.submission_serial_number</code>.
     */
    public final TableField<TallCanonicalRecord, Long> SUBMISSION_SERIAL_NUMBER = createField(DSL.name("submission_serial_number"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>analytics.tall_canonical.activity_uid</code>.
     */
    public final TableField<TallCanonicalRecord, String> ACTIVITY_UID = createField(DSL.name("activity_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>analytics.tall_canonical.org_unit_uid</code>.
     */
    public final TableField<TallCanonicalRecord, String> ORG_UNIT_UID = createField(DSL.name("org_unit_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>analytics.tall_canonical.team_uid</code>.
     */
    public final TableField<TallCanonicalRecord, String> TEAM_UID = createField(DSL.name("team_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>analytics.tall_canonical.assignment_uid</code>.
     */
    public final TableField<TallCanonicalRecord, String> ASSIGNMENT_UID = createField(DSL.name("assignment_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>analytics.tall_canonical.submission_id</code>.
     */
    public final TableField<TallCanonicalRecord, String> SUBMISSION_ID = createField(DSL.name("submission_id"), SQLDataType.VARCHAR(26).nullable(false), this, "");

    /**
     * The column <code>analytics.tall_canonical.submission_uid</code>.
     */
    public final TableField<TallCanonicalRecord, String> SUBMISSION_UID = createField(DSL.name("submission_uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>analytics.tall_canonical.template_uid</code>.
     */
    public final TableField<TallCanonicalRecord, String> TEMPLATE_UID = createField(DSL.name("template_uid"), SQLDataType.VARCHAR(11).nullable(false), this, "");

    /**
     * The column <code>analytics.tall_canonical.template_version_uid</code>.
     */
    public final TableField<TallCanonicalRecord, String> TEMPLATE_VERSION_UID = createField(DSL.name("template_version_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>analytics.tall_canonical.instance_key</code>.
     */
    public final TableField<TallCanonicalRecord, String> INSTANCE_KEY = createField(DSL.name("instance_key"), SQLDataType.CLOB.nullable(false), this, "");

    /**
     * The column <code>analytics.tall_canonical.canonical_element_id</code>.
     */
    public final TableField<TallCanonicalRecord, UUID> CANONICAL_ELEMENT_ID = createField(DSL.name("canonical_element_id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>analytics.tall_canonical.element_path</code>.
     */
    public final TableField<TallCanonicalRecord, String> ELEMENT_PATH = createField(DSL.name("element_path"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>analytics.tall_canonical.repeat_instance_id</code>.
     */
    public final TableField<TallCanonicalRecord, String> REPEAT_INSTANCE_ID = createField(DSL.name("repeat_instance_id"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>analytics.tall_canonical.parent_instance_id</code>.
     */
    public final TableField<TallCanonicalRecord, String> PARENT_INSTANCE_ID = createField(DSL.name("parent_instance_id"), SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>analytics.tall_canonical.repeat_index</code>.
     */
    public final TableField<TallCanonicalRecord, Integer> REPEAT_INDEX = createField(DSL.name("repeat_index"), SQLDataType.INTEGER, this, "");

    /**
     * The column <code>analytics.tall_canonical.value_text</code>.
     */
    public final TableField<TallCanonicalRecord, String> VALUE_TEXT = createField(DSL.name("value_text"), SQLDataType.CLOB, this, "");

    /**
     * The column <code>analytics.tall_canonical.value_number</code>.
     */
    public final TableField<TallCanonicalRecord, BigDecimal> VALUE_NUMBER = createField(DSL.name("value_number"), SQLDataType.NUMERIC, this, "");

    /**
     * The column <code>analytics.tall_canonical.value_bool</code>.
     */
    public final TableField<TallCanonicalRecord, Boolean> VALUE_BOOL = createField(DSL.name("value_bool"), SQLDataType.BOOLEAN, this, "");

    /**
     * The column <code>analytics.tall_canonical.value_json</code>.
     */
    public final TableField<TallCanonicalRecord, JSONB> VALUE_JSON = createField(DSL.name("value_json"), SQLDataType.JSONB, this, "");

    /**
     * The column <code>analytics.tall_canonical.value_ref_uid</code>.
     */
    public final TableField<TallCanonicalRecord, String> VALUE_REF_UID = createField(DSL.name("value_ref_uid"), SQLDataType.VARCHAR(11), this, "");

    /**
     * The column <code>analytics.tall_canonical.value_ref_type</code>.
     */
    public final TableField<TallCanonicalRecord, String> VALUE_REF_TYPE = createField(DSL.name("value_ref_type"), SQLDataType.VARCHAR(64), this, "");

    /**
     * The column
     * <code>analytics.tall_canonical.submission_creation_time</code>.
     */
    public final TableField<TallCanonicalRecord, LocalDateTime> SUBMISSION_CREATION_TIME = createField(DSL.name("submission_creation_time"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>analytics.tall_canonical.start_time</code>.
     */
    public final TableField<TallCanonicalRecord, LocalDateTime> START_TIME = createField(DSL.name("start_time"), SQLDataType.LOCALDATETIME(6), this, "");

    /**
     * The column <code>analytics.tall_canonical.created_at</code>.
     */
    public final TableField<TallCanonicalRecord, LocalDateTime> CREATED_AT = createField(DSL.name("created_at"), SQLDataType.LOCALDATETIME(6).nullable(false).defaultValue(DSL.field(DSL.raw("now()"), SQLDataType.LOCALDATETIME)), this, "");

    /**
     * The column <code>analytics.tall_canonical.updated_at</code>.
     */
    public final TableField<TallCanonicalRecord, LocalDateTime> UPDATED_AT = createField(DSL.name("updated_at"), SQLDataType.LOCALDATETIME(6), this, "");

    private TallCanonical(Name alias, Table<TallCanonicalRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TallCanonical(Name alias, Table<TallCanonicalRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment("Canonical tall analytics table. instance_key = COALESCE(repeat_instance_id, submission_uid) used for idempotency"), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>analytics.tall_canonical</code> table reference
     */
    public TallCanonical(String alias) {
        this(DSL.name(alias), TALL_CANONICAL);
    }

    /**
     * Create an aliased <code>analytics.tall_canonical</code> table reference
     */
    public TallCanonical(Name alias) {
        this(alias, TALL_CANONICAL);
    }

    /**
     * Create a <code>analytics.tall_canonical</code> table reference
     */
    public TallCanonical() {
        this(DSL.name("tall_canonical"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Analytics.ANALYTICS;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.IDX_TALL_CANONICAL_PARENT_INSTANCE, Indexes.IDX_TALL_CANONICAL_REPEAT_INSTANCE, Indexes.IDX_TALL_CANONICAL_SUBMISSION_UID, Indexes.IDX_TALL_CANONICAL_TEMPLATE_ELEMENT, Indexes.IDX_TALL_CANONICAL_TEMPLATE_VERSION_ELEMENT, Indexes.IDX_TALL_CANONICAL_UPDATED_AT, Indexes.IDX_TALL_VALUE_REF_UID);
    }

    @Override
    public Identity<TallCanonicalRecord, Long> getIdentity() {
        return (Identity<TallCanonicalRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<TallCanonicalRecord> getPrimaryKey() {
        return Keys.PK_TALL_CANONICAL;
    }

    @Override
    public List<UniqueKey<TallCanonicalRecord>> getUniqueKeys() {
        return Arrays.asList(Keys.UQ_TALL_INSTANCE_CANONICAL);
    }

    @Override
    public TallCanonical as(String alias) {
        return new TallCanonical(DSL.name(alias), this);
    }

    @Override
    public TallCanonical as(Name alias) {
        return new TallCanonical(alias, this);
    }

    @Override
    public TallCanonical as(Table<?> alias) {
        return new TallCanonical(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TallCanonical rename(String name) {
        return new TallCanonical(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TallCanonical rename(Name name) {
        return new TallCanonical(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TallCanonical rename(Table<?> name) {
        return new TallCanonical(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TallCanonical where(Condition condition) {
        return new TallCanonical(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TallCanonical where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TallCanonical where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TallCanonical where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TallCanonical where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TallCanonical where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TallCanonical where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TallCanonical where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TallCanonical whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TallCanonical whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
